### ISSUE TITLE
Improve NASA CDF installation experience; make pycdf.download_library useful

### ISSUE THREAD

**Issue by drsteve** [spacepy/spacepy#122]
The NASA CDF library is required for many (most?) users of SpacePy, but it's never been the easiest to install. It's also one of the FAQs for SpacePy.

I'd really like to investigate some ways of making it easier to install CDF with SpacePy.
For example:
- on install try to download and build CDF
   - easy on posix systems; harder on Windows (but doable, esp. in conda)
   - note that the Windows installer from NASA requires admin, so we can't rely on that
- build CDF and include it with the releases so that there's a functional CDF provided
   - this has the down-side of not having up-to-date CDF in case of leap-second updates, etc.
- `spacepy.pycdf.download_library` exists, but isn't usable without *already having CDF installed*
   - `spacepy.pycdf` won't import without CDF installed, so download_library isn't usable unless CDF is already present
   - `download_library` has very limited platform support anyway
- if `download_library`  can be made useful across platforms, then it can also serve as an update function to help the user stay up-to-date

**Comment by jtniehof** [comment]
Note the comment right on the commit for download_library: "No way to call it since the library needs to be installed for import, tbd."

That followed on from a lot of work to unpick import/find library/load library. So yes, the plan is to prompt the user if they want to install the library if finding it fails. What's needed is a reliable way to determine if the user can actually answer the question. See https://python-forum.io/Thread-detect-if-sys-stdin-is

Then, yes, we can work on Mac and Linux support. I don't want to try building the CDF library on Windows; if the user has to confirm a UAC prompt, I think that's reasonable.

This has languished because getting a release out was a higher priority.

**Comment by drsteve** [comment]
Agreed.

I opened the issue to have it on **the list** rather than just as something you probably remember was on your horizon at some point. It's possible that a discussion here might prompt some new options.

Maybe it'd be useful to include CDF build instructions for Windows in the Windows build documentation? (Noting, of course, that the installer is the easy option if you have admin.) The conda environment we specify should allow a direct build from source, though I haven't tried this yet.

**Comment by jtniehof** [comment]
Agreed with having it tracked!

**Comment by jtniehof** [comment]
The CDF library will be included with binary wheels (and the PR implementing that will close this issue).
