### ISSUE TITLE
cannot import name 'irbempylib' from 'spacepy.irbempy'

### ISSUE THREAD

**Issue by heptacle** [spacepy/spacepy#134]
Spacepy doesn't work.

### Minimal example to reproduce issue:

```
from spacepy.coordinates import Coords                                  
y=Coords([[1,2,4],[1,2,2]],'GEO','car')  
```

### Error message/Traceback:

```
ImportError                               Traceback (most recent call last)
<ipython-input-2-da18c6fd86b6> in <module>
----> 1 y=Coords([[1,2,4],[1,2,2]],'GEO','car')

~/anaconda3/lib/python3.7/site-packages/spacepy/coordinates.py in __init__(self, data, dtype, carsph, units, ticks)
     87     def __init__(self, data, dtype, carsph, units=None, ticks=None):
     88 
---> 89         from . import irbempy as op
     90         from spacepy.irbempy import SYSAXES_TYPES as typedict
     91 

~/anaconda3/lib/python3.7/site-packages/spacepy/irbempy/__init__.py in <module>
     69 
     70 
---> 71 from .irbempy import *
     72 

~/anaconda3/lib/python3.7/site-packages/spacepy/irbempy/irbempy.py in <module>
     29 import spacepy.datamodel as dm
     30 try:
---> 31     from . import irbempylib as oplib
     32 except ImportError:
     33     if 'sphinx' in sys.argv[0]:

ImportError: cannot import name 'irbempylib' from 'spacepy.irbempy' (/Users/jjung11/anaconda3/lib/python3.7/site-packages/spacepy/irbempy/__init__.py)
```

### OS, Python version, and dependency version information:

```
Darwin-18.2.0-x86_64-i386-64bit
sys.version_info(major=3, minor=7, micro=1, releaselevel='final', serial=0)
numpy=1.16.3
scipy=1.3.0
matplotlib=3.1.0
```

Uninstalling and reinstalling didn't work.
I also tried 
pip install https://github.com/spacepy/spacepy/zipball/master
but that version didn't work either.
When I downgraded the Spacepy from 0.1.6 to 0.1.5, it worked.

Can someone help me to use 0.1.6 properly?

**Comment by drsteve** [comment]
Thanks for opening the issue. The probable cause here is that the IRBEM library didn't compile successfully. 
My guess is that underlying cause of this is basically the set of issues raised in #90 and #108.

Installing from pip with `numpy`>=1.16.0 won't work with the release that's currently on PyPI. Our next release is pending a few fixes wot Windows-specific issues, but when it's ready 0.1.7 will resolve this issue. Installing spacepy from the master branch of this repository should work.

Can I ask for more information about what didn't work when you tried installing from the git repo using pip? Without error messages we can't diagnose the failure.

Since you have previously installed 0.1.5 you should have all of the prerequisites, so building from source should work. Can I also please ask you to try downloading the source code (go to the main page of our repo (https://github.com/spacepy/spacepy) and hit the green button marked "clone or download". Select the option "download zip" and save the file. Unpack that archive using `unzip spacepy-master.zip` (or whatever compression utility you prefer to use) and change into the spacepy directory.
Run
```
python setup.py install --user 2>&1 | tee diagnostics.txt
```

If there are any issues with the installation, please attach the file `diagnostics.txt` to a comment here so we can see why the build is failing. There are no current known issues in spapcey itself that should cause a failure to build from source. As long as numpy and C/Fortran compilers are present everything should build and `spacepy.irbempy` should be available.

**Comment by heptacle** [comment]
Installing from the git repo using pip didn't have any problem. The problem was in running the code. It has same problem as I posted. (ImportError: cannot import name 'irbempylib' from 'spacepy.irbempy' (/Users/jjung11/anaconda3/lib/python3.7/site-packages/spacepy/irbempy/__init__.py))

For the building from source, I attached diagnostics.txt generated following your comment.
[diagnostics.txt](https://github.com/spacepy/spacepy/files/3218913/diagnostics.txt)

By the way, , I was also trying 0.1.5 version for my work, but it also failed. 

```
In [7]: y=Coords([[1,0,0]],'GEI','sph')                                         
In [8]: y.ticks=Ticktock(datetime.datetime(2008,1,11,12,36,14),'UTC')           
In [9]: x=y.convert('GSE','car')                                                
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-e2f7bf5745f3> in <module>
----> 1 x=y.convert('GSE','car')
~/anaconda3/lib/python3.7/site-packages/spacepy/coordinates.py in convert(self, returntype, returncarsph)
    313         if (self.dtype != returntype) :
    314             assert NewCoords.ticks, "Time information required; add a.ticks attribute"
--> 315             NewCoords.data = op.coord_trans( self, returntype, returncarsph)
    316             NewCoords.dtype = returntype
    317             NewCoords.carsph = returncarsph
~/anaconda3/lib/python3.7/site-packages/spacepy/irbempy/irbempy.py in coord_trans(loci, returntype, returncarsph)
    921 
    922         xout[i,:] = oplib.coord_trans1(sysaxesin, sysaxesout, \
--> 923             iyear, idoy, secs, loci.data[i])
    924 
    925     # add  sph to car or v/v convertion if initial sysaxesout was None
TypeError: irbempylib.coord_trans1() 1st argument (sysaxesin) can't be converted to int
```

I'm not sure but I think it's related to same problem, because it mention irbempylib.

I have a feeling that my Fortran compiler is somewhat not working properly for this installation, but I have no idea for how to fix it so I'd appreciate any help.

**Comment by drsteve** [comment]
Just a quick update... There was still an incompatibility with GCC8, so your attempt to build from source was extremely helpful.

I've rolled together both a fix to that issue, and an update to the IRBEM library. One of our other developers is reviewing my fixes/updates, and when he's done there it'll get merged with the master branch in this repository. As soon as that happens this issue will be closed.

So when this issue closes (and you should get an email telling you about that), you should be able to get the source again (same method as before) and build. If you hit any more issues after that please let us know!

**Comment by drsteve** [comment]
@heptacle We've updated the IRBEM library as well as fixing the remnant incompatibilities with GCC8. If you grab the latest source again and build from that you shouldn't see this problem any more. Let us know if there are still issues! 
Thanks!
