### ISSUE TITLE
Handle ffnet dependency with binary install

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#160]
Right now we hard-require ffnet in our setup.py declarations. That means even with a binary wheel built for Windows, doing a pip install on Windows will require a Fortran compiler for ffnet (and appropriate flags on the install.)

Long-term maybe we can contribute a wheel to ffnet. Short-term we can make LANLstar an "extra" (in setuptools terms). This means:
`pip install spacepy`

will not grab ffnet. (Of course, installing ffnet later would still allow LANLstar to work.) To make sure ffnet works you'd have to do:
`pip install spacepy[LANLstar]`

Now, long-term we also are talking about splitting LANLstar into a "kits" or something so this'll be a bit weird (how-to-get-LANLstar will change) but again, we're shooting for good short-term fixes right now.

Assuming we're okay with this, it should be possible to still hard-require ffnet on other platforms. (For that matter, we can also skip the "extras" thing and just tell people to install ffnet themselves if they want LANLstar on Windows.)

This is turning into multiple-choice, so:

1. Require a Fortran compiler to install a binary wheel on Windows (current)
2. Declare LANLstar an "extra" so you have to install SpacePy in a funny way to get ffnet and LANLstar working
    1. Do this on all platforms
    2. Do this just on Windows while having ffnet still base-required on other platforms
3. Do not require ffnet on Windows so people have to install ffnet explicitly on Windows, but will get it automatically on other platforms.

@drsteve ? @balarsen ?

**Comment by balarsen** [comment]
I really like the kits idea personally.

As an example: I have been using [uproot](https://github.com/scikit-hep/uproot) a lot lately and there they broke it into the core and an [uproot-methods](https://github.com/scikit-hep/uproot-methods) packages. The later is more community input with the first being core. 

My take is something like spacepy as a core then spacepy-pycdf, spacepy-lanlstar, etc to handle external dependencies. This might also serve as a sandbox to have things that are less vetted and more bleeding edge. One could image a pandas based datamodel and things like that.

**Comment by drsteve** [comment]
I'm, unsurprisingly, in support of the breakup into "kits". However, I am opposed to breaking out the core datamodel stuff, and our NASA CDF support is right at the heart of that.

- `LANLstar` should be broken out into a dependent package
- `pybats` should probably be broken out into a dependent package
- `radbelt` (or whatever it's called) should be either broken out into a dependent package or just shot into the Sun
- `coordinates` and `irbempy` need to be approached with care since we currently use `irbempy` for `coordinates`. However, `coordinates` should kept as core, with a different implementation for the transforms, IMO. `irbempy` should be a dependent package.

`datamodel` should be core. If that's not core then what is "core" `spacepy` providing? `toolbox`? `empiricals`? For my money those aren't _purposeful_ enough to warrant a package. And CDF hits our core demographic of space scientists.

**Comment by balarsen** [comment]
I hear the cdf part. One other way to think on this is that if it is a odd external dependency (fortran, cdf, etc) then it should be a kit. But overall I don't have strong feelings here.
