### ISSUE TITLE
Broken link on https://pythonhosted.org/SpacePy/

### ISSUE THREAD

**Issue by rweigel** [spacepy/spacepy#270]
The "Homepage" link at https://pythonhosted.org/SpacePy/ points to http://spacepy.lanl.gov/index.shtml, which returns a HTTP 404.

**Comment by jtniehof** [comment]
Unfortunately we don't have control of pythonhosted.org. I clicked the link on PyPI to delete docs from pythonhosted.org (since they no longer accept updates) and all that happened was the delete button went away. If you know of a way to kill it off, it would be appreciated.

Failing that, link to https://spacepy.github.io/ as much as possible so we can drive it up in the Google ranks.

**Comment by rweigel** [comment]
I have not used pythonhosted.org before. But it seems to be the page I come to when I search for SpacePy. I recall a few times concluding the project was dormant based on the dates on the bottom of the page.

I did find this https://github.com/pypa/pypi-legacy/issues/288

**Comment by jtniehof** [comment]
Yes, there are lots of issues and PRs on PyPI dealing with documentation deletion, and they all are "okay, you can do it now," basically puting in place the delete button that I used and didn't do anything.

As I'm sure you know, we can't control what page comes up when people search for SpacePy.

I'll try filing a PyPI bug.

**Comment by rweigel** [comment]
I noticed that the project that the person wanted to delete that prompted https://github.com/pypa/pypi-legacy/issues/288 still exists. Very unfortunate.

**Comment by jtniehof** [comment]
Thanks for digging that up. That's not a promising sign.

**Comment by jtniehof** [comment]
The PyPI folks fixed this for us...it all now redirects to github (and to the correct page!) Thanks to them and thanks to you for bringing it up; that prompted me to get in touch with PyPI.
