### ISSUE TITLE
test coverage: irbempy

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#307]
irbempy init is 100% coverage, but the real work in irbempy is 45% covered. 

- find_LCDS is untested, as is find_LCDS_K. I wonder if we could use lgmpy to determine "truth" and compare.
- get_AEP8 has a lot of exceptional cases not handled, but prints out. Maybe these should be warnings or exceptions.
- _get_Lstar when nAlpha == 0
- get_Lm --again, can use lgmpy, as that's pretty heavily tested for this.
- get_Lstar

Hard to test:
- updateTS07Coeffs downloads data and could probably be hit with an integration test

**Comment by drsteve** [comment]
The LCDS will be tricky to get a "ground truth" (Jay and I wrote a whole article about how problematic it is). Honestly `find_LCDS` is unphysical, because it does the search for a given pitch angle rather than for a fixed K. However, that was how a number of folks did it for quite a while. The "physical" one is to do the search at fixed K. All of this is slower than molasses though. Maybe for `find_LCDS_K` we can spot-test against the IRBEM results given in the supplemental information for Albert et al. (https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1029/2018JA025991)

For `get_Lm` and `get_Lstar` I'd want to clarify exactly what we're testing. Are we testing the accuracy of the IRBEM library? Our wrapping of it? Both? It'd be easy enough to whip up a test file with LANLGeoMag if we're looking for an accuracy test, but we'd need to bear in mind that we only expect a certain degree of similarity given how each library is constructed. Certainly we'd expect very similar results in the inner magnetosphere under not-to-extreme conditions.

**Comment by drsteve** [comment]
Also, any tests for IRBEM veracity will be affected by merging #295 since it fixes a bug in one of the coordinate transforms (also affecting testing for #302 ) and updates IGRF.

**Comment by jtniehof** [comment]
I should be able to get to #295 tomorrow, fingers crossed.

Honestly for a lot of these, we're pretty sure they work, so this is more in the realm of regression testing. So does our wrapping work and do we return reasonable values. I'm perfectly comfortable allowing pretty huge deltas as long as stuff 1) doesn't blow up 2) isn't completely nonsensical. So for L* I don't care about 5 vs 6, just don't want 100. Or -5.6e34.

**Comment by jtniehof** [comment]
Up to 46%, not exactly a seismic change. _get_Lstar with nAlpha==0 is set, but the rest stand (including a good chunk of get_Lstar itself.)

**Comment by jtniehof** [comment]
#749 has a lot of updates so it's worth branching off that instead of `main`, and checking what the coverage actually is.

**Comment by jamesw732** [comment]
#749 has us up to 81% coverage for spacepy/irbempy/__init__.py. Pretty good baseline, might actually be stretched pretty thin to improve that by a significant amount.
