### ISSUE TITLE
Pinned dependencies on CI

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#31]
Continuous integration builds on pull requests shouldn't fail just because a dependency has been updated, so we should probably pin versions there.

**Comment by balarsen** [comment]
I think we likely want both pinned dependency for testing ourself but also a version for when a dependency changes. It becomes our problem and we might as well know about it ASAP. Using pip and requirements.txt it’s possible to skip versions, have min and max, a just max I suppose so knowing where we work helps our build work as often as possible. I have seen other packages group their badges this way.

**Comment by drsteve** [comment]
This was also raised in #32. We should expand the CI to test not just specific Python versions, but also specific older versions of dependencies. That's obviously in addition to how we're doing it now which uses the latest releases. This is veering into the territory of several other issues right now.

- Setting versions requirements (and any exclusions) falls under #8 
- Testing specific dependency versions is wrapped up with some of the other CI issues. including #30  and #32
- Reporting test results is in #15 

This issue should be closed with Travis updates that test with specific older versions of dependencies. Actually, I think I'll close #32 since we have a regular build that is running (see [travis-ci.com/spacepy/spacepy/builds](https://travis-ci.com/spacepy/spacepy/builds). There's no sense waiting to expand the tested versions there when we already have another issue tracker for that.

**Comment by drsteve** [comment]
I've started a build matrix in the Travis YML file and I'm testing against a number of numpy versions and Python versions. The different configs can be seen on the [latest build status for that branch](https://travis-ci.com/drsteve/spacepy/builds/86221874).

This branch currently *just* does pinned versions, so I need to bring it back to testing both pinned versions *and* latest versions.
