### ISSUE TITLE
_get_Lstar TypeError when loci class is in GSM

### ISSUE THREAD

**Issue by Rhyst223** [spacepy/spacepy#330]
I am trying to use the `spacepy.irbempy._get_Lstar` function where the loci input has coordinates (GSM,'sph').

When attempting to run I get the following error:

`TypeError: irbempylib.make_lstar_shell_splitting1() 5th argument (sysaxes) can't be converted to int`

Now, I can get around this if I convert to GEO first and then run the function, but this seems like an unnecessary step.

Is it just the case that the `spacepy.irbempy._get_Lstar` does not work with GSM?
### Minimal example to reproduce issue:

```
Traceback (most recent call last):
  File "./parallel_space_array.py", line 185, in <module>
    do_work(week, last, options, pool)
  File "./parallel_space_array.py", line 132, in do_work
    result = pool.map(Lcalc_wrapper, inputs, chunksize = 1)
  File "/rds/general/user/rlt1917/home/anaconda3/envs/py27/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/rds/general/user/rlt1917/home/anaconda3/envs/py27/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
TypeError: irbempylib.make_lstar_shell_splitting1() 5th argument (sysaxes) can't be converted to int
```

### OS, Python version, and dependency version information:
 Python 3.6 and Python 2.7

### Version of SpacePy
 Same problem for most recent SpacePy in Python 3 and 2

**Comment by jtniehof** [comment]
It would be helpful to have an example to reproduce rather than just the traceback. The public interface is `get_Lstar` not `_get_Lstar`, but I'm able to call either with GSM:

```
import spacepy.coordinates
import spacepy.irbempy
import spacepy.time

c = spacepy.coordinates.Coords([[3, 0, 0]], dtype='GSM', carsph='car')
t = spacepy.time.Ticktock(['2015-01-01'])
spacepy.irbempy.get_Lstar(t, c)
spacepy.irbempy.irbempy._get_Lstar(t, c, [90])
```

**Comment by Rhyst223** [comment]
Apologies for omitting a working example. I have just tried again and the issue appears to be with spherical coordinates in the Coords object.

```
import spacepy.coordinates
import spacepy.irbempy
import spacepy.time

c = spacepy.coordinates.Coords([[3, 25, 360]], dtype='GSM', carsph='sph')
t = spacepy.time.Ticktock(['2015-01-01'])
spacepy.irbempy.get_Lstar(t, c)
spacepy.irbempy.irbempy._get_Lstar(t, c, [90])
```

and I get the following Traceback:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-e0b7242926ad> in <module>
      5 c = spacepy.coordinates.Coords([[3, 25, 360]], dtype='GSM', carsph='sph')
      6 t = spacepy.time.Ticktock(['2015-01-01'])
----> 7 spacepy.irbempy.get_Lstar(t, c)
      8 spacepy.irbempy.irbempy._get_Lstar(t, c, [90])

~/anaconda3/envs/pysatref/lib/python3.6/site-packages/spacepy/irbempy/irbempy.py in get_Lstar(ticks, loci, alpha, extMag, options, omnivals)
   1711         DALL = reassemble(result)
   1712     else: # single NCPU, no chunking
-> 1713         DALL = _get_Lstar(ticks, loci, alpha, extMag, options, omnivals)
   1714 
   1715     return DALL

~/anaconda3/envs/pysatref/lib/python3.6/site-packages/spacepy/irbempy/irbempy.py in _get_Lstar(ticks, loci, alpha, extMag, options, omnivals)
   1443         lm, lstar, bmirr, bmin, xj, mlt = oplib.make_lstar_shell_splitting1(nTAI, nalpha, \
   1444             d['kext'], d['options'], d['sysaxes'], d['iyearsat'], d['idoysat'], d['utsat'], \
-> 1445             d['xin1'], d['xin2'], d['xin3'], d['degalpha'], d['magin'])
   1446 
   1447     else:

TypeError: irbempylib.make_lstar_shell_splitting1() 5th argument (sysaxes) can't be converted to int
```

**Comment by drsteve** [comment]
I can take a look at this later, but chances are that the issue is because
IRBEM supports a smaller set of coordinate systems as input than we do.
Spherical GSM coordinates, for example, are not supported by IRBEM (GSM is
assumed to be Cartesian under the hood there). My guess is that our
internal conversion to a system for IRBEM is somehow not providing an
integer value to identify the coordinate system.

To work around, I would suggest either doing the conversion ahead of time,
or using Cartesian GSM rather than spherical. We should be able to get this
tracked down and fixed fairly quickly though.

**Comment by drsteve** [comment]
It looks like I misremembered a conversion in `spacepy.irbempy.prep_irbem`
Basically, the issue here is that IRBEM assumes that any given coordinate system is cartesian or spherical, i.e., GDZ, SPH and RLL are all spherical, everything else is assumed cartesian. The checks when we bundle the inputs to pass to IRBEM assume that the coordinate system is already in a type IRBEM supports - so the system check returns `None` for unsupported systems like spherical GSM. `None` can't be converted to an integer-type for setting the coordinate system in IRBEM, hence the error.

We should be catching that and converting. Honestly I thought we'd fixed that, but there's no time like the present. I'll submit a fix in a minute.
