### ISSUE TITLE
Stdout flooded by the welcome message

### ISSUE THREAD

**Issue by Septaris** [spacepy/spacepy#346]
When using spacepy to open a CDF file and stream the content to stdout, the welcome message appears in the stream (leading to app crashes downstream).

For the moment, I use the following code as a work around:

```python
try:
    # keep track of the previous stdout value
    stdout_ = sys.stdout
    stream = io.StringIO()
    sys.stdout = stream
    from spacepy.pycdf import CDF
    # restore the previous stdout
    sys.stdout = stdout_
except Exception as exc:
    raise Exception("Error during spacepy import") from exc
```

But it is a bit tedious. Do you have another solution? Is this message really useful ?

Note: the message disappears once the .spacepy folder is created which makes the error somewhat unpredictable.

**Comment by jtniehof** [comment]
Thanks for bringing this up.

I'm not sure I'd go for streaming a CDF file to stdout since I suspect that might cause some other issues. But I can see sometimes a particular use case backs you into a corner.

As you've noticed, if `.spacepy` exists, it doesn't print the message, so making .spacepy (even better, setting up a `.spacepyrc`) is probably the best way to make sure you get the behavior you want. You can `os.makedirs(os.path.join('~', '.spacepy'))` before the import and life should be reasonably good. Or can you set the SPACEPY environment variable, see all these tricks in the [configuration docs](https://spacepy.github.io/configuration.html).

I'm certainly open to changing this behavior. I think it makes sense to check if stdout is a tty before printing the message. I'd like to hear from other devs on approaches we can take to reduce/eliminate the messages on import.

1. If we print anything, we probably do need the "SpacePy" header.
2. Do we need to print out the license/citation information? Citation is front-and-center on the webpage.
3. Since we are writing to the user's homedir, I like the idea of letting them know, and providing the information of where it is. We could maybe alleviate this by making the configuration information more prominent on the webpage (again). And make a note of finding the directory using `DOT_FLN`.
4. We can warn about the need to update the leapseconds potentially on the first import of spacepy.time instead of spacepy? Keeping track of that might be a pain. Maybe we need a more fine-grained warning of old leapseconds file. Making these warning rather than print statements might also be helpful.
5. OMNI does warn if you import it without having OMNI data. Last time we discussed this, the cited pathology was somebody who installed spacepy, imported it once to make sure it worked, and then proceeded to get on an airplane and try to use the omni module without doing an update. That conversation was something like six years ago; do we think that pathology still applies? And again, we can maybe make these warnings so they're trappable.

We could also look at doing another pass of the "Quick Start" and making that more prominent on the main page.

**Comment by balarsen** [comment]
I am a fan of "it just works". I would vote for killing off the printed spacepy message. On the directory, failing gracefully seems like a good plan. 

Tons of things write silently to home so I don't feel compelled to more than document that we write there.

**Comment by spacecataz** [comment]
For 1, perhaps a .spacepyrc setting to turn off the welcome message/header would be a useful utility?
In terms of 2, I don't think that print is necessary.  I very rarely see other packages do this.
With #4, making it a "warn" seems like a good fix.
5: The omni message is important as it's relevant to functionality...

**Comment by jtniehof** [comment]
@spacecataz : The existence of spacepyrc turns off the welcome message, so a config setting there doesn't really help. For 5, omni already warns on import...do you think we still need a note to run update when importing top-level spacepy?

**Comment by spacecataz** [comment]
@jtniehof Roger dodger on 1; for five, I would lean towards keeping the the top-level OMNI warning.  It's very quick to update the OMNI database and about as much work as creating spacepyrc.  I could be convinced otherwise...

**Comment by jtniehof** [comment]
It's actually now fairly slow to update omni once we pull in the dailies from NMC to get current coverage, and ideally I'd like to get rid of all nag messages on original import.
