### ISSUE TITLE
Sphinx >=1.8.0 incompatible with spacepy docs build

### ISSUE THREAD

**Issue by balarsen** [spacepy/spacepy#35]
The new sphinx build deprecates and removes sphinx.ext.pngmath extension so the docs won't build. We will need to play with what versions work and backwards compatibility etc. One solution would be setting a max version on sphinx at 1.7.9 for the time being. 

http://www.sphinx-doc.org/en/master/contents.html#

**Comment by balarsen** [comment]
```
No pre-built documentation, attempting to build...
Running Sphinx v1.8.1

Extension error:
Could not import extension sphinx.ext.pngmath (exception: No module named 'sphinx.ext.pngmath')

```

**Comment by jtniehof** [comment]
It's replaced with something wicked easy like imgmath so we just need to require the minimum version that has that and search-replace. I don't think it should be too hard.

**Comment by jtniehof** [comment]
It's replaced with something wicked easy like imgmath so we just need to require the minimum version that has that and search-replace. I don't think it should be too hard. It might even be possible to do some sort of version check and either-or it.

**Comment by balarsen** [comment]
Yep, I just found that `imgmath` is the replacement. Wonder if that is back compat? I'll check and put in a pull request if so otherwise will need help,

**Comment by balarsen** [comment]
The change to `imgmath` from `pngmath` works back to sphinx 1.4 (released Mar 28, 2016). Should I commit my fixes and do a pull that means we need sphinx>=1.4?

**Comment by drsteve** [comment]
So the question is... should we expect anyone who is building the docs to have a recent version of Sphinx? It's probably not too unreasonable, although I note that my Sphinx was installed using apt (Ubuntu 16.04LTS) and is version 1.3.6. I should probably uninstall and reinstall from pip.

If we're good with bumping this version requirement - and it's pretty soft since it's for building docs - then I'm happy for #37 to be merged.

**Comment by jtniehof** [comment]
I was going to just comment on @balarsen 's PR but since it's sort of tough to edit a PR, as @drsteve found, seems to make more sense just to submit a new PR. I do think we should stick with the "previous LTS" standard where at all possible, and it's pretty easy to do that here.

See also scikit-learn-contrib/project-template#26 (although I took a better-to-ask-forgiveness approach instead).
