### ISSUE TITLE
Repeated "not supported" message when running test_irbem on Windows

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#36]
When I'm running from master on Windows, I get this repeated "not supported" message, as if spacepy were being reloaded or something. This might actually be a reload or there might be something odd going on in the import machinery. I'll look into it but wanted to log as an issue in case I forget...haven't even verified if it happens on other OSs.

**Comment by jtniehof** [comment]
It doesn't look like this is going to be fixable. No state carries over to the child process, so it doesn't know if it's a fresh import or a multiprocessing spawn. That also means it has to read the configuration file at multiprocessing startup and it might not be the same as when the parent process started!

For these particular functions, have we checked that it needs to be multiprocessing and threading would be insufficient? Too much shared IRBEM state? I believe f2py calls should drop the GIL.

@drsteve , @balarsen , what do you think? I think this might just be a close as wontfix.

**Comment by drsteve** [comment]
I really don't care that this affects the test, but presumably it affects any use of the multiprocessing calls in irbempy.

Since the "not supported" message doesn't appear in the release versions it should be quieter in those, but that still leaves the underlying issues you mention. We'll need to take a closer look to see whether we can change how the multiprocessing is done here without issues. The underlying Fortran uses common blocks all over the place, so doing the parallelization in a convenience routine and then calling that is out.

**Comment by jtniehof** [comment]
I'm going to close this as wontfix in a week if there are no further comments.

**Comment by drsteve** [comment]
Closing as a 'wontfix', since this has basically gone stale and that was the status at last comment.

**Comment by jtniehof** [comment]
Agreed.
