### ISSUE TITLE
pycdf.istp.FileChecks.all() fails on CDF_CHAR

### ISSUE THREAD

**Issue by msbentley** [spacepy/spacepy#394]
I am a first-time user of spacepy, and was primarily trying to use the ISTP checks on some CDF files I want to beat into ISTP compliance. This particular file contains a CDF_CHAR*19 column, and `pycdf.istp.FileChecks.all()` chokes on a value range test when trying to compare a string and an integer:

```
~/miniconda3/envs/spacepy/lib/python3.8/site-packages/spacepy/pycdf/istp.py in _validhelper(cls, v, rng)
    323                 if firstdim: #Add pseudo-record dim
    324                     attrval = numpy.reshape(attrval, (1, -1))
--> 325             if numpy.any((attrval < minval)) or numpy.any((attrval > maxval)):
    326                 errs.append('{} ({}) outside data range ({},{}).'.format(
    327                     which, attrval[0, :] if multidim else attrval,

TypeError: '<' not supported between instances of 'str' and 'int'
```

### OS, Python version, and dependency version information:
```
Linux-4.18.0-18-lowlatency-x86_64-with-glibc2.10
sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
numpy=1.19.1
scipy=1.5.2
matplotlib=3.3.0
```

### Version of SpacePy
0.2.1 from pip

Please let me know if you need more information!

**Comment by jtniehof** [comment]
Hi Mark--

Almost always this means that the VALIDMIN/VALIDMAX is not the same CDF type as the variable. Most commonly I've seen this with numerical types having VALIDMIN/MAX or FILLVAL as strings. #361 includes a fix to be more graceful in these situations. That's been merged on to master and will be in the next release (see https://github.com/spacepy/spacepy/projects/5 for release status.)

The pycdf checker was meant to be complementary to the checker available as part of the skeleton editor at https://spdf.gsfc.nasa.gov/skteditor/ , so I do recommend running that as well. Sometimes that will show up issues that cause trip-ups with the more complicated checks done in pycdf.

Since you're running matplotlib 3.3, you should also be aware of #381...this doesnt affect pycdf but does affect other areas of SpacePy.

**Comment by msbentley** [comment]
Thanks @jtniehof - I'm also new to CDF, as  you can probably tell ;-) I'll check out the skeleton editor. You're quite right, the file has:
```     VALIDMIN        (CDF_CHAR/1): "0"
     VALIDMAX        (CDF_CHAR/3): "255"
     FILLVAL         (CDF_CHAR/2): "-1"```

for a field which is `CDF_CHAR/19`!

Thanks for your time, I'll close this now!
