### ISSUE TITLE
Problems with plot.utils.EventClicker

### ISSUE THREAD

**Issue by jwoodroffe** [spacepy/spacepy#4]
I'm using SpacePy with Python 3.6.4 (Anaconda 64-bit). When attempting to use EventClicker from plot.utils, I receive the following error:

  File "/Users/jwoodroffe/anaconda/lib/python3.6/site-packages/spacepy/plot/utils.py", line 358, in _add_event_phase
    ls=self._styles[self._curr_phase / len(self._colors) % len(self._styles)])
TypeError: list indices must be integers or slices, not float

This is due to a change in how division is handled between Python 2.x and 3.x. When fixed by changing "/" to "//", another error occurs nearby:

File "/Users/jwoodroffe/anaconda/lib/python3.6/site-packages/spacepy/plot/utils.py", line 359, in _add_event_phase
    if not self._xydata is None:
AttributeError: 'EventClicker' object has no attribute '_xydata'

If I fix this by initializing _xydata to None in __init__, I get:

  File "/Users/jwoodroffe/anaconda/lib/python3.6/site-packages/spacepy/plot/utils.py", line 394, in _add_event_phase
    self._data_events.resize((self._data_events.shape[0] + 1,
AttributeError: 'NoneType' object has no attribute 'resize'

And so on. This particular code may be in need of some TLC.

**Comment by jnlanl** [comment]
Yeah, we haven't touched this code since we published the paper it was written for, and matplotlib has changed a lot in that time. I'll take a look.

**Comment by drsteve** [comment]
Following the example in the docstring in Python 3.5.2 leads to the first error. Correcting this from ```/``` to ```//``` then works for me.

While that can be trivially fixed (and needs to be) it sounds like there's another issue that may not be related to the 2 to 3 transition.

Reading through the code, it looks like it's possible to hit a case where _xydata is undefined, but only where no line objects exist in the first plot. Since there are traps for NaN or Inf limits, as well as various other traps, I believe this likely occurs when EventClicker is used on a non-line plot (e.g., output from pcolormesh or scatter, which use QuadMesh and PathCollection respectively). @jwoodroffe Let us know if that's actually the case here... if the data weren't >1D, or otherwise non-line plot, can you give us a minimal example?
