### ISSUE TITLE
hackthon RaspiOS Buster results

### ISSUE THREAD

**Issue by scivision** [spacepy/spacepy#441]
The setup is a Raspberry Pi 4 with default, current Raspberry Pi OS (Buster) and default system Python and GCC. SpacePy is f546d9f6. CDF 3.8.

```
GNU Fortran (Raspbian 8.3.0-6+rpi1) 8.3.0
Linux-5.4.51-v7l+-armv7l-with-debian-10.6
sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
numpy=1.17.4
scipy=1.5.2
matplotlib=3.1.1
````

```sh
$ pytest --continue-on-collection-errors
```

```
platform linux -- Python 3.7.3, pytest-6.1.2, py-1.9.0, pluggy-0.13.0
rootdir: /home/pi/code/spacepy
collected 1558 items / 2 errors / 1556 selected
...
= 116 failed, 1424 passed, 10 skipped, 8 xfailed, 4 warnings, 2 errors in 158.18s (0:02:38) =
```

[spacepy.log](https://github.com/spacepy/spacepy/files/5507983/spacepy.log)

**Comment by jtniehof** [comment]
Thanks for running those. I don't think we're going to get much useful out of the log, unfortunately. Running `pytest` instead of the `test_all.py` script finds a lot of scripts that aren't part of the actual test suite. It also imported from the source tree instead of the installed version, so none of the IRBEM-backed code worked (since there was no built library.) Finally there are some issues from running outside of the test directory that are being worked down (#178).

**Comment by jtniehof** [comment]
Due to the issues in my previous comment, and the fact that I've run the tests successfully, I'm closing as not an issue.
