### ISSUE TITLE
pip install fails to resolve dependencies under python 3 (PyPI) or when installing from git

### ISSUE THREAD

**Issue by drsteve** [spacepy/spacepy#45]
As discussed in #38, installing in a clean environment using ```pip``` only works under Python 2, installing from PyPI. It fails under Python 3, and under both 2 and 3 when pointing to a git repo, e.g., 
```
pip install git+https://github.com/spacepy/spacepy
```

To reproduce
```
~/.local/bin/virtualenv -p python3 py3-clean
cd py3-clean/
source bin/activate
pip3 install spacepy
```

or
```
~/.local/bin/virtualenv py2-clean
cd py2-clean/
source bin/activate
pip install git+https://github.com/spacepy/spacepy
```

This should yield
```
Collecting git+https://github.com/spacepy/spacepy
  Cloning https://github.com/spacepy/spacepy to /tmp/pip-req-build-FI27ko
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-FI27ko/setup.py", line 24, in <module>
        from numpy.distutils.core import setup
    ImportError: No module named numpy.distutils.core
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-FI27ko/
```

It seems likely that the issue is that we import numpy at the top of the ```setup.py``` which means that an ImportError is raised before we even get to running the setup function. It's unclear why it works under pip2 with PyPI as the source, but it does...

**Comment by jtniehof** [comment]
Thanks for the legwork. This is going to suck. Using the numpy distutils was necessary to get all the fortran to work properly. It replaces setup, and the install_requires are kwargs to setup.

I've had to do a bunch of stuff on Windows to de-numpy the C compilations, so I'd love to axe numpy distutils, but that's going to take a lot of Fortran legwork.

What I hope is that pip does an initial egg_info call that I can catch and use base setuptools then, and otherwise import the numpy stuff (so on the actual install we'll get that.)

**Comment by jtniehof** [comment]
Incidentally, do we want to use the 0.1.7 milestone or just the release project? Since we can't do any discussion on the milestone maybe we should just forget about them.

**Comment by balarsen** [comment]
Just as a mostly redundant FYI, if one installs numpy then spacepy will install just fine. 
```
~/.local/bin/virtualenv -p python3 py3-clean
cd py3-clean/
source bin/activate
pip3 install numpy
pip3 install spacepy
```

**Comment by drsteve** [comment]
Re-upping this as I think we should get a new release before the summer season of workshops (GEM, CEDAR). I'd be fine leaving this issue for the following update. We can trivially add instructions to install numpy prior to installing spacepy and then have a clean-up of the setup as a top priority for 0.1.8.

Thoughts?

**Comment by jtniehof** [comment]
Agreed this is not an absolute blocker on next release. I want people to have a good install experience with our first release in a long time, but don't need everything to be fixed.

My main concern is to get the Windows bugs knocked down because I won't feel 100% confident in the whole compiler setup there until everything's really working. Sorry I haven't had much time to commit.
