### ISSUE TITLE
time: DeprecationWarning: Converting `np.integer` or `np.signedinteger` to a dtype is deprecated.

### ISSUE THREAD

**Issue by balarsen** [spacepy/spacepy#462]
Test tests for `time` raise a few `DeprecationWarning` instances. 

### Minimal example to reproduce issue:
```
 python test_time.py -v TimeClassTests.testDataPersistsRDT
```
also
```
python test_time.py -v TimeFunctionTests.test_days1958toTAI
```

### Error message/Traceback:
```
testDataPersistsRDT (__main__.TimeClassTests)
Verify input data is returned for RDT input ... /home/balarsen/miniconda3/envs/python3/lib/python3.8/site-packages/numpy/core/_asarray.py:136: DeprecationWarning: Converting `np.integer` or `np.signedinteger` to a dtype is deprecated. The current result is `np.dtype(np.int_)` which is not strictly correct. Note that the result depends on the system. To ensure stable results use may want to use `np.int64` or `np.int32`.
  return array(a, dtype, copy=False, order=order, subok=True)
```

```
test_days1958toTAI (__main__.TimeFunctionTests)
Test fractional days since 1958 to TAI ... /home/balarsen/miniconda3/envs/python3/lib/python3.8/site-packages/numpy/core/_asarray.py:136: DeprecationWarning: Converting `np.integer` or `np.signedinteger` to a dtype is deprecated. The current result is `np.dtype(np.int_)` which is not strictly correct. Note that the result depends on the system. To ensure stable results use may want to use `np.int64` or `np.int32`.
  return array(a, dtype, copy=False, order=order, subok=True)
```

### OS, Python version, and dependency version information:
```
Linux-4.4.0-18362-Microsoft-x86_64-with-glibc2.10
sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
numpy=1.19.4
scipy=1.5.4
matplotlib=3.3.3
```

### Version of SpacePy
376539978a44189faf433695ae169f102edac9b2

**Comment by balarsen** [comment]
A bit more digging to find the place where this occurs

```
import spacepy.time as spt
spt.Ticktock([10000]*10, 'RDT')
/home/balarsen/miniconda3/envs/python3/lib/python3.8/site-packages/numpy/core/_asarray.py:136: DeprecationWarning: Converting `np.integer` or `np.signedinteger` to a dtype is deprecated. The current result is `np.dtype(np.int_)` which is not strictly correct. Note that the result depends on the system. To ensure stable results use may want to use `np.int64` or `np.int32`.
  return array(a, dtype, copy=False, order=order, subok=True)
```

**Comment by jtniehof** [comment]
> ```python
> leap_tai[ldidx]
> array([-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf])
> ```

No, that's fine, assuming you're in a case where all the times of interest are pre-1957. The TAI of the period when TAI-UTC==0 (i.e. before the first leap second) is set to -inf so that we always have a match to the TAI-UTC array. It's not strictly correct, of course, but UTC isn't strictly defined before than anyhow.

> Seems numpy is driving toward requiring more specificity.

We've dealt with lots of these before so I can go back and check. It's annoying when all you want is "make it an integer." But in this case it's obvious...it should be the same as taiutcidx, or `np.intc`.

**Comment by balarsen** [comment]
@jtniehof 

What is the thinking on `np.intc`? 

From https://numpy.org/devdocs/user/basics.types.html I see `np.intc` is "Platform-defined", is that better or is being specific to `np.int32` desired? Mostly want to understand rather than a particular horse in this.

**Comment by jtniehof** [comment]
Yes, since it's used as an array index, we want it to be sized according to an array index, and usual C convention is "pointers and indices are sized as int." One could possibly make an argument for `intp`, which should _not_ be in the "fixed-size aliases" section of that document because it's not a fixed size!

Based on [this](https://numpy.org/doc/stable/reference/arrays.indexing.html#detailed-notes) I think it's worth changing both instances to `intp`. They are explicitly arrays of numpy indices.

**Comment by balarsen** [comment]
OK, so explained that way it makes good sense. Likely we have a lot of `np.intXX` that should all be `np.intp` but for another day. 

I will make the change.
