### ISSUE TITLE
spacepy.irbempy import error, possibly due to circular import.

### ISSUE THREAD

**Issue by anthony2352** [spacepy/spacepy#535]
I am receiving what I believe to be a circular import error in the terminal when I go to import spacepy.irbempy.

### Minimal example to reproduce issue:

This problem seems similar to what was suggested in #134, so I first did what was suggested there. I removed my current spacepy distribution, then I cloned the source code from the git repository. using

```
git clone https://github.com/spacepy/spacepy.git
```
I believe that this should have cloned the latest version of spacepy.  To complete the build, I ran

```
python3 setup.py install --user 2>&1 | tee diagnostics.txt
```

### Error message/Traceback:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-1d24b0e07465> in <module>
----> 1 import spacepy.irbempy as ir

~/.local/lib/python3.8/site-packages/spacepy/spacepy/irbempy/__init__.py in <module>
     69 
     70 
---> 71 from .irbempy import *
     72 

~/.local/lib/python3.8/site-packages/spacepy/spacepy/irbempy/irbempy.py in <module>
     28 import spacepy.coordinates as spc
     29 import spacepy.datamodel as dm
---> 30 from . import irbempylib as oplib
     31 import spacepy.toolbox as tb
     32 

ImportError: cannot import name 'irbempylib' from partially initialized module 'spacepy.irbempy' (most likely due to a circular import) (/home/knightac/.local/lib/python3.8/site-packages/spacepy/spacepy/irbempy/__init__.py)

```
This is the exact error message that I was receiving previously, before I removed spacepy and then cloned and built it from the git. As requested in #134, here is [diagnostics.txt](https://github.com/spacepy/spacepy/files/6735537/diagnostics.txt) from the build.

### OS, Python version, and dependency version information:

```
Linux-3.10.0-1160.31.1.el7.x86_64-x86_64-with-glibc2.10
sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
numpy=1.19.2
scipy=1.5.2
matplotlib=3.3.2
```
### Version of SpacePy

I downloaded spacepy from https://github.com/spacepy/spacepy. I believe that this would have downloaded the latest version, which is 0.2.2.

**Comment by drsteve** [comment]
Thanks for the report... and especially for including the diagnostic output.
It looks like `IRBEM` built correctly in this case (from a quick read), so it seems unlikely that that's the issue. 

I typed out a huge set of questions and possible thoughts here before I hit on the issue...
A few things (because I don't know _why_ this happens, just how):
1. `IRBEM` looks like it built correctly, that's unlikely to be the problem
2. The path in the final line of the traceback shouldn't exist (`~/.local/lib/python3.8/site-packages/spacepy/spacepy`), and almost certainly doesn't.

I believe you're using an anaconda installation to get your python, based on the diagnostic output. If that's the case you shouldn't need to use the `--user` flag when you build. Just make sure that anaconda is activated and that you're in the anaconda environment you want to use (this could be the base environment, that's fine).

Can I ask you to:
1. Remove the current install location
    `rm -rf ~/.local/lib/python3.8/site-packages/spacepy`
2. Ensure that anaconda is activated
    `conda activate` (might be `source activate` depending on your system)
3. (Optional: activate a different conda environment if that's what you usually work in)
4. Install without `--user`
    `python setup.py install`
    It should install to wherever anaconda keeps local environments... if anaconda was installed as root you may hit errors here and need to create a local environment first. E.g., `conda create ...`
5. Test from home directory
    ```
    cd
    python
    >>> import spacepy.irbempy
    ```

Assuming that then works for you, I still don't know why a user installation doesn't work under anaconda. Perhaps @jtniehof will have an idea or two?

**Comment by anthony2352** [comment]
The issue seems to be resolved now. spacepy.irbempy now imports with no errors and seems to be functioning properly. I merely repeated the same process, and somehow it was successful the second time.
Thank you!
