### ISSUE TITLE
bug in multiprocessing

### ISSUE THREAD

**Issue by janetcgreen** [spacepy/spacepy#537]
My issue is ...

irbempy.get_Lstar will sometimes return a vector of L values that is shorter than the input coords which is caused by a bug related to the setup for multiprocessing. Below is the block of code with the fix

        for block in range(nblocks):
            startind = block*blocklen
            if block != nblocks-1: #not last block
                endind = block*blocklen + blocklen
            else:
                # 
                # BUG: Old code below does not always go to the end of the data
                #endind = block*blocklen + 2*blocklen #going past the end of an array in a slice is fine
                # FIX: new line of code below
                endind = ncalc # Setting endind to ncalc for the final block ensures that this works correctly
            tt.append(ticks[startind:endind]) #chunk time tags
            cc.append(loci[startind:endind]) #chunk positions
            if omnivals:
                ov.append(get_ov(omnivals, startind, endind))

**Comment by drsteve** [comment]
Thanks @janetcgreen - I've not been able to figure out any edge-cases where the tactic of applying a double-sized chunk at the end won't index past the final item... however, your solution is simple and direct because it just uses the (known) index of the last item. I'm not saying they aren't there, just that I couldn't figure out how to hit your issue. 

With that in mind I've rolled your fix into my updates for a different issue, and it'll get merged in once I've written unit tests...
