### ISSUE TITLE
'nan' for T96 external field model

### ISSUE THREAD

**Issue by anthony2352** [spacepy/spacepy#538]
I am receiving an 'nan' for all values corresponding to the 'Blocal' and 'Bvec' keys using spacepy.irbempy.get_bfield() when I set the external magnetic field model as T96.

### My code:

Here is my code:
```
import spacepy.time as spt
import spacepy.coordinates as spc
import spacepy.irbempy as ir
t = spt.Ticktock(['2003-10-29T07:00:00'],'ISO')
y = spc.Coords([2,0,0],'GEO','car')
print(ir.get_Bfield(t,y,extMag = 'T96'))

```

### Output:

Here is the output:
```
{'Blocal': array([nan]), 'Bvec': array([[nan, nan, nan]])}
```

### OS, Python version, and dependency version information:

Linux-3.10.0-1160.31.1.el7.x86_64-x86_64-with-glibc2.10
sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
numpy=1.19.2
scipy=1.5.2
matplotlib=3.3.2

### Version of SpacePy

My spacepy version is 0.2.2, and I cloned it from the git repository.

**Comment by drsteve** [comment]
Thanks for the report!

While looking into this I noticed that the `nan` return was only happening for a short interval around the time in your example. That led me to investigate the inputs that the model was taking...

The root cause here is that the underlying IRBEM library imposes limits on the input parameters - these are documented in [Table 4 of McCollough et al., 2008](https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2008SW000391#swe273-tbl-0004). For the interval that's in your example the magnitude of By is larger than 10 nT and thus outside the allowed limits.

This isn't documented in our `irbempy` documentation, so I'm going to tag this issue as a documentation issue.
