### ISSUE TITLE
Ubuntu 16.04 to be removed from GH Actions (impacts tests for 3.5)

### ISSUE THREAD

**Issue by drsteve** [spacepy/spacepy#550]
We just got hit by one of the "brown outs" for Ubuntu 16.04 on the GH actions test runner. https://github.com/spacepy/spacepy/actions/runs/1233777812

Basically, Ubuntu 16.04 is being removed from GH actions (https://github.com/actions/virtual-environments/issues/3287) on September 20th. Both of our Python 3.5 builds are on 16.04 images.

[Our dependency chart](https://spacepy.github.io/dep_versions.html) suggests we could drop explicit 3.5 testing, which I'd be happy enough with. But we do need to figure out what our solution is fairly quickly...

**Comment by jtniehof** [comment]
My thought was to start rolling up 3.x versions once the 2.7 removal is complete. My thought was to fairly aggressively remove support for pre-3.5 (i.e., drop 3.2-3.4 shortly after finishing dropping 2.7.)

It probably won't hurt to use deadsnakes PPA in the short term. That would also let us explicitly test 3.2 in the meantime.

We also could just drop the 3.5 testing without changing our supported minimum, which is in theory 3.2 although not tested in CI.

Third option is to move to explicitly setting up venvs or similar instead of using system Python in the CI.

My inclination is to try out deadsnakes.

**Comment by drsteve** [comment]
In order of least work, it's probably:
1. drop 3.5 testing without changing supported minimum
2. use deadsnakes PPA and test whichever versions we want (I'd probably stay with >=3.5)
3. switch everything to venvs/conda

Since the various [3.x (x<=4) all hit EOL](https://devguide.python.org/devcycle/#end-of-life-branches) before Python 2.7 I'm not at all concerned about testing on them. I'd also be fine dropping support for them at the same time as dropping 2.7 support (or even earlier since our 2.7 phase-out is so prolonged).

**Comment by hugovk** [comment]
How about dropping 3.2-3.5 right now?

Here's the second principle of [dependency version support](https://spacepy.github.io/dep_versions.html):

> 2. Support for old versions of dependencies will be dropped only for reason, e.g. if a new version is required to support a new feature or fix a bug. Maintenance of convoluted workarounds is included in this category.

Sounds like this principle perfectly fits this case.

The download share of EOL versions is very low too. Here's the pip installs for spacepy from PyPI for August 2021:

| category | percent | downloads |
| -------- | ------: | --------: |
| 3.7      |  29.16% |       577 |
| 3.8      |  24.20% |       479 |
| null     |  20.87% |       413 |
| 3.6      |  13.49% |       267 |
| 3.9      |  10.66% |       211 |
| 2.7      |   1.36% |        27 |
| 3.5      |   0.25% |         5 |
| Total    |         |     1,979 |

Source: `pip install -U pypistats && pypistats python_minor spacepy --last-month`
