### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [spacepy/spacepy#569]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
lokal$ perl -p -i.orig -0777 -e 's/^(?<indentation>\s+)(?<target>\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+\-%&|^@]|\*\*?|\/\/?|<<|>>)/$+{indentation}$+{target} $+{operator}=/gm' $(find ~/Projekte/SpacePy/lokal -name '*.py')
```

**Comment by jtniehof** [comment]
I see at least 13 issues open in other repositories with nearly identical wording; this appears to be found (and perhaps opened) with an automated source code analysis tool. This does not suggest any actual improvement to SpacePy, and the devs will not apply blind transformations to the entire codebase.

PRs for style (e.g. PEP8) cleanup are still welcome, but should be comprehensive in scope (i.e. fix more than one thing).

**Comment by elfring** [comment]
>I see at least 13 issues open in other repositories with nearly identical wording;

Several software components are affected in similar ways.


>this appears to be found (…) with an automated source code analysis tool.

💭 Would you like to take another look at the shown Perl command example which demonstrates a source code search and replacement approach?


>This does not suggest any actual improvement to SpacePy, …

Do you care for the application of augmented assignment statements at all (in this software)? :thinking:

**Comment by drsteve** [comment]
1. It seems to be several hundred judging by the number of bad faith issues that were opened.
2. Not really. Asking folks to run obsfucated perl instead of providing a PR is obnoxious.
3. Sure. Sometimes. But if this was an actual human who had actually looked at the code you'd see that it gets used occasionally, where appropriate.
4. It’s your birthday. Someone gives you a calfskin wallet.
5. You’ve got a little boy. He shows you his butterfly collection plus the killing jar.
6. You’re watching television. Suddenly you realize there’s a wasp crawling on your arm.
7. You’re in a desert walking along in the sand when all of the sudden you look down, and you see a tortoise, it’s crawling toward you. You reach down, you flip the tortoise over on its back. The tortoise lays on its back, its belly baking in the hot sun, beating its legs trying to turn itself over, but it can’t, not without your help. But you’re not helping. Why is that?

Finally, here are a couple of links out of the possible hundreds that support this position.
Exhibit A - https://github.com/sympy/sympy/issues/22440
Exhibit B - https://github.com/zeromq/pyzmq/issues/1630

**Comment by jtniehof** [comment]
It's pretty clear from the wider context that this is either a bot unleashed in bad faith or a person acting in bad faith. The issue is closed and, since that didn't appear to get the point across, I'm also locking the conversation. Further spam from this account will result in it being banned and reported to GitHub, although since it's already been reported repeatedly I'm not optimistic.
