### ISSUE TITLE
ZLIB_ERROR: Error during ZLIB decompression.

### ISSUE THREAD

**Issue by nsioulas** [spacepy/spacepy#570]
I have been getting the following error:

**ZLIB_ERROR: Error during ZLIB decompression.**

when I am trying to load Solar Orbiter CDF files. 

 I have downloaded the files using the code provided here https://issues.cosmos.esa.int/solarorbiterwiki/display/SOSP/SOAR+%28Solar+Orbiter+Archive%29+-+How+to+Use#SOAR(SolarOrbiterArchive)HowtoUse-python_access

I am using windows

### Minimal example to reproduce issue:

```

from   spacepy import pycdf
import glob
import os


target_path =r"C:\Users\nokni\sunpy\data"
file_names  = glob.glob(target_path+os.sep+'*.cdf')                          
for i in range(len(file_names)):
    #""" Load magnetic field data """
    B= pycdf.CDF(file_names[i])
```

### Error message/Traceback:

![image](https://user-images.githubusercontent.com/74452161/143174042-175c069d-4248-4434-86d4-937a9b7f39c5.png)

 **OS, Python version, and dependency version information:**

```
Windows-10-10.0.19041-SP0
sys.version_info(major=3, minor=8, micro=2, releaselevel='final', serial=0)
numpy=1.21.2
scipy=1.5.4
matplotlib=3.3.3
```

**Comment by drsteve** [comment]
I *think* I've seen this before, but can we get a little extra information to help track this down?

1. What version of spacepy are you using and how did you install it?
2. What version of the CDF library are you using and how did you install it? (There's more than one Windows installer, so as much detail as possible would really help).

I'll be able to check tomorrow, but I think where I've seen this before it was a CDF library installation issue, such that CDF didn't have permission to open a temporary file to uncompress the data. In that case we did resolve it, so I'm hopeful that it's not going to be too hard here.

**Comment by nsioulas** [comment]
Thanks for the prompt reply!

I am using:
spacepy==0.2.2
cdflib==0.3.20

It's been over a year so I can't quite remember. I think I have just followed the directions outlined in the spacepy readme file

Thanks again!

**Comment by jtniehof** [comment]
SpacePy 0.2.3 has been out for nearly a month, so I suggest upgrading. cdflib is completely irrelevant here. You can get the version of the CDF library you're using with:
```python
print(spacepy.pycdf.lib.version)
```

I wish Solar Orbiter provided direct file downloads rather than having to install several packages. I presume you're using the snippet titled "Python code to get files". Can you provide the time, level, and identifier you're using, and/or attach one of the files so we have a real apples-to-apples comparison?

**Comment by nsioulas** [comment]
The code that I am using to download the files:
```
import sunpy_soar
from sunpy.net import Fido

from sunpy.net.attrs import Instrument, Level, Time
from sunpy_soar.attrs import Identifier


instrument = Instrument('MAG')
time = Time('2020-05-01', '2021-10-05')
level = Level(2)
identifier = Identifier('MAG-SRF-NORMAL')

result = Fido.search(instrument, time, level, identifier)
print(result)


files = Fido.fetch(result)
print(files)
```

- I could not attach the file as it is not supported

-  My version of CDF library is :
       (3, 7, 1, b'0')

Thank you!

**Comment by drsteve** [comment]
From my notes on the previous time I saw this:
1. This is probably an issue with the environment not allowing the NASA CDF library to write temporary files, which blocks the decompression of CDFs that were compressed at the file level rather than the variable level.
2. SpacePy provides a full-featured interface to the NASA CDF library (which you would have obtained from https://cdf.gsfc.nasa.gov/html/sw_and_docs.html at some point), so to test where the issue arises it's good to reproduce the issue _outside_ of python. That is, CDF should also provide a command line tool called `cdfdump`. Running `cdfdump` on the file should result in the same error.
3. Please check where the following environment variables point: `CDF_TMP`, `TEMP`, and `TMP`. It's most likely to be the first one here...  They should all point to locations in your user account and should _not_ point to locations that require administrative privileges. If `TEMP` and `TMP` point to an accessible location in your user account and `CDF_TMP` doesn't, go to your account settings and change `CDF_TMP` to point to the same location as the others.

Hopefully that helps. Please let us know the outcome so we can update this issue and hopefully document it so that others will be able to fix it more easily.

**Comment by jtniehof** [comment]
You can check all these with just e.g.:
```python
import os
print(os.environ['CDF_TMP'])
```

One clarification to Steve's notes: unless you have a reason, usually `CDF_TMP` shouldn't be set at all.

**Comment by drsteve** [comment]
TBF, that was actual feedback from the CDF team, so it's entirely possible that one of their windows installers does set it.

**Comment by jtniehof** [comment]
I'll do some more detailed digging over the weekend, it just involves firing up VMs and setting up conda envs and such. We'll get this documented as specifically as possible.

**Comment by nsioulas** [comment]
The environment variables point to:

![image](https://user-images.githubusercontent.com/74452161/143299451-cd205fbc-62cb-467e-bb55-932366fa5470.png)

I am not so experienced with environment variables. I have tried to change CDF_TMP to point to the same folder as TMP and TEMP

![image](https://user-images.githubusercontent.com/74452161/143299649-63dd19ac-f873-4b98-9416-cd2e728de920.png)

This didn't make a change.

**Comment by drsteve** [comment]
Just to cut this down to a manageable reproduction I've reduced the time range you're searching so it only finds one file (rather than 410, which takes too long to download and isn't relevant to the problem).
```
import sunpy_soar
from sunpy.net import Fido
from sunpy.net.attrs import Instrument, Level, Time
from sunpy_soar.attrs import Identifier

instrument = Instrument('MAG')
time = Time('2020-05-01', '2020-06-01')
level = Level(2)
identifier = Identifier('MAG-SRF-NORMAL')

result = Fido.search(instrument, time, level, identifier)
files = Fido.fetch(result)

import spacepy.pycdf as cdf
data = cdf.CDF(files[0])
```
This works for me with my CDF install as mentioned above and `CDF_TMP` pointing to user/appdata/local/temp. I can then make it fail by setting the temp location to a non-user-writeable location:
```
import os
os.environ['CDF_LIB'] = 'C://Windows/'
data = cdf.CDF(files[0])
```
and this reproduces the `ZLIB_ERROR`.
If I switch back to a writeable location:
```
os.environ['CDF_LIB'] = 'C://Users/Steven/'
data = cdf.CDF(files[0])
```
I can once again read the file without error.


The traceback, when it fails, is identical to that above:
```
---------------------------------------------------------------------------
CDFError                                  Traceback (most recent call last)
<ipython-input-21-b8f0691b38ff> in <module>
----> 1 data = cdf.CDF(files[0])

~\Miniconda3\envs\py38_64\lib\site-packages\spacepy\pycdf\__init__.py in __init__(self, pathname, masterpath, create, readonly)
   1746         self._opened = False
   1747         if masterpath is None and not create:
-> 1748             self._open(True if readonly is None else readonly)
   1749         elif masterpath:
   1750             self._from_master(masterpath.encode())

~\Miniconda3\envs\py38_64\lib\site-packages\spacepy\pycdf\__init__.py in _open(self, readonly)
   1926         """
   1927
-> 1928         lib.call(const.OPEN_, const.CDF_, self.pathname, ctypes.byref(self._handle))
   1929         self._opened = True
   1930         if readonly: #Default is RW

~\Miniconda3\envs\py38_64\lib\site-packages\spacepy\pycdf\__init__.py in call(self, *args, **kwargs)
    639                 ), kwargs['ignore'])
    640         else:
--> 641             return self.check_status(self._library.CDFlib(
    642                 *(args + (const.NULL_, ))
    643                 ))

~\Miniconda3\envs\py38_64\lib\site-packages\spacepy\pycdf\__init__.py in check_status(self, status, ignore)
    592             return status
    593         if status < const.CDF_WARN:
--> 594             raise CDFError(status)
    595         else:
    596             warning = CDFWarning(status)

CDFError: ZLIB_ERROR: Error during ZLIB decompression.
```
and the `CDF_TMP` environment variable was pointing to a non-user-writeable location. I'm going to say that _is_ the issue here. My guess would be that, if it's still raising the same exception, the environment variable wasn't correctly updated.

I'm going to tag this as both upstream (because it's a NASA CDF issue, not a SpacePy issue) and documentation (because `pycdf`/`datamodel` users will come here for help first, generally).

**Comment by nsioulas** [comment]
Thanks so much!

I re-did what you suggested earlier (i.e., changing the path of CDF_TMP) and seems to working great now!


Thank you so much for your time!

**Comment by jtniehof** [comment]
I'm reopening just so we don't lose sight of the documentation needs here (but glad it's working for you!)

**Comment by jtniehof** [comment]
Note that 3.7.1, 3.8.0.1, and 3.8.1 all appear to use different installers, so I need to investigate this on all of those.
