### ISSUE TITLE
Coordinates: Nonsense value returned in conversion to GDZ spherical coordinates

### ISSUE THREAD

**Issue by rebeccaringuette** [spacepy/spacepy#577]
Another example for an error resulting from a conversion _to_ GDZ spherical _from_ GEO spherical
```py
cvals = Coords([[1.063871355909377, -90.0, -180.0], [1.063871355909377, 0.0, 0.0], [1.063871355909377, 90.0, 180.0]], 'GEO', 'sph')
tt = Ticktock(ts_to_spacepystr([1068865200 1068865200 1068865200]), 'ISO')
cvals.ticks = tt
newC = cvals.convert('GDZ','sph')
```
output for newC:
Coords( [[-13119.519017475252, -90.0, -180.0], [400.00018276982473, 3.530478404585919e-15, 0.0], [406.0143894752504, 90.0, 180.0]] , 'GDZ', 'sph')
Note the same times and radii are given for each coordinate set, but different latitudes and longitudes are used. The first value returned for altitude in km is obviously nonsensical. The same value is returned when a longitude of 180 is used instead of -180 (equivalent position). This causes errors in code layers built on top of this in Kamodo (https://github.com/nasa/Kamodo).

Request: a layer be added to check for and correct these types of errors.

This also begs the question of why the returned altitudes differ at all for the same time and radius with differing latitude and longitudes. My initial guess is that the Earth is assumed to be non-spherical?

**Comment by drsteve** [comment]
Thanks for the report.
Addressing the last question first, yes, GDZ is geodetic coordinates given as altitude [km], latitude [deg], longitude [deg]. Geodetic altitudes are relative to a reference ellipsoid, so in general, the altitude and latitude are different between geocentric geographic coordinates (GEO) and geodetic coordinates (GDZ). Longitude is the same in both systems.

I've put together a reproducible example (I assume that `ts_to_spacepystr` is a Kamodo function? And just a note here that converting to a numeric system supported by `spacepy.time` rather than ISO8601 strings might buy you good performance gains if you have large arrays of times):
```
import spacepy.time as spt
import spacepy.coordinates as spc

tt = spt.Ticktock(['2012-06-13T15:00:00', '2012-06-13T15:00:00', '2012-06-13T15:00:00'])
spc.Coords([[1.063871355909377, -90.0, 360.0], [1.063871355909377, -90.0, 0.0], [1.063871355909377, 90.0, 180.0]], 'GEO', 'sph', ticks=tt).convert('GDZ', 'sph')
```
and the result is then
```
Coords( [[-13119.519017475252, -90.0, -1.4033418597069752e-14], [-13119.519017475252, -90.0, 0.0], [406.0143894752504, 90.0, 180.0]] , 'GDZ', 'sph')
```

The underlying calculation is done in the IRBEM library, and the altitude is blowing up at singularities in the geodetic conversion. So in that sense this probably needs fixing upstream. To illustrate, if we move slightly away from the combinations of coordinate axes:
```
spc.Coords( [[421.38521728372234, -89.99999990062808, -1.4033418597069752e-14], [421.38521728372234, -89.99999990062808, 0.0], [406.0143894752504, 90.0, 180.0]] , 'GDZ', 'sph')
```
we get:
```
Coords( [[421.38521728372234, -89.99999990062808, -1.4033418597069752e-14], [421.38521728372234, -89.99999990062808, 0.0], [406.0143894752504, 90.0, 180.0]] , 'GDZ', 'sph')
```

And if we move directly to the fortran call (i.e., skipping our object and interface):
```
geo = spc.Coords([[1.063871355909377, -90.0, 360.0], [1.063871355909377, -90.0, 0.0], [1.063871355909377, 90.0, 180.0]], 'GEO', 'sph', ticks=tt).convert('GEO', 'car')
iyear = geo.ticks.UTC[0].year
idoy = geo.ticks.DOY[0]
secs = geo.ticks.UTC[0].hour*3600 + geo.ticks.UTC[0].minute*60.0 + geo.ticks.UTC[0].second

from spacepy.irbempy import irbempylib

irbempylib.coord_trans1(1, 0, iyear, idoy, secs, geo.data[0])
```
which returns
```
array([-1.31195190e+04, -9.00000000e+01, -1.40334186e-14])
```
Which is pretty strong evidence that it's upstream. That's something we can trap in the `Coords` class, but it's probably a more robust fix to trap it in the IRBEM GDZ algorithm.

So what I'm going to do here is tag this as both a bug and as upstream. Then:
- look into a patch for IRBEM
- look into trapping the problematic singularities on the SpacePy side
- write some unit tests for the failure
- ensure that the `Coords` wrapper is handling these cases correctly in both master and the new backend that's under development

**Comment by rebeccaringuette** [comment]
Thanks for the explanation of the GDZ coordinate system, and for the prompt and detailed response.
Yes, ts_to_spacepystr is a function, defined below. Apologies for not catching that. Also, I will pass the speed recommendation to the correct person on our team.
```py
@np.vectorize
def ts_to_spacepystr(ts):
    return dt.strftime(dt.utcfromtimestamp(int(ts)), '%Y-%m-%dT%H:%M:%S')
```

In this case, the error appears pretty easy to catch (radius/altitude < 0). I had the thought of either printing an error message and not returning any coordinate conversion result with a negative radius/altitude, at least on our side, but a fancier solution may be more useful. Maybe there could be some sort of iteration where a nearly correct value could be obtained by iterating the lat, lon, and time coordinate values by small amounts and averaging the returned values. I haven't noticed any similar issue in cartesian coordinates for any coordinate system.

**Comment by jtniehof** [comment]
To the efficiency aside, Ticktock directly supports Unix timestamps, so no need to go converting to datetime and then to ISO (also supports datetimes directly). Assuming your example has commas:
```python
timestamps = [1068865200, 1068865200, 1068865200]
tt = spacepy.time.Ticktock(ts_to_spacepystr(timestamps), 'ISO')
print(tt.UTC)
tt2 = spacepy.time.Ticktock(timestamps, 'UNX')
print(tt2.UTC)
```

**Comment by rebeccaringuette** [comment]
I was just working on the efficiency using the direct datetime approach, but this looks faster. I didn't know there was direct support for timestamps (maybe add this to the documentation?). Thanks, Jon. Does the direct timestamp support assume UTC for the timestamps? For instance, should I use
```py
tt2 = spacepy.time.Ticktock(timestamps, 'UTC')
```
to tell the TickTock instance that the timestamps given are in UTC?

**Comment by drsteve** [comment]
In `spacepy.time`:
- 'UTC' means timezone-naive (i.e., nominal UTC timezone) datetime objects.
- 'UNX' is the UNIX timestamp, and Jon can correct me here, assumes UTC. As far as I'm aware UNIX time is UNIX time everywhere and is UTC-referenced (so timezone offsets shouldn't be present).

**Comment by drsteve** [comment]
> In this case, the error appears pretty easy to catch (radius/altitude < 0). I had the thought of either printing an error message and not returning any coordinate conversion result with a negative radius/altitude, at least on our side, but a fancier solution may be more useful. Maybe there could be some sort of iteration where a nearly correct value could be obtained by iterating the lat, lon, and time coordinate values by small amounts and averaging the returned values. I haven't noticed any similar issue in cartesian coordinates for any coordinate system.
So the geodetic conversion is handled quite differently from all other conversions. The other coordinate systems are all essentially defined as Cartesian systems and rotation matrices are calculated to convert between them. Any necessary conversions between user-provided (or requested) spherical systems are handled under the hood.

Calculating geodetic coordinates is done from Cartesian geocentric geographic using one of a range of algorithms for the conversion, and they're generally iterative already. The algorithm used by IRBEM is an iterative algorithm. There is a closed-form solution (Heikkinen's method) that will be used in the new coordinates backend. The issue is that there are singularities in the solutions that are handled differently by different algorithms, and that's not going to be seen in any of the other coordinate transformations because the conversion uses rotation matrices. So this will only affect the geodetic systems (GDZ and RLL).

If the issue is that the altitude is blowing up at the South pole (I _think_ the North pole is fine here) then probably the thing to do is to calculate the altitude for the equivalent position in the opposite hemisphere. Alternatively, since the conversion happens from Cartesian GEO, we could trap for Southern polar positions (X=Y=0, Z -ve). There'd need to be a different trap for the equatorial singularity... and at that point I wonder whether it wouldn't just be easier to replace the IRBEM geodetic algorithm with Heikkinen's method.

Calculating geocentric geographic from geodetic is trivial.

Fixing this will be straightforward, it's just a matter of figuring out the best/fastest/most efficient way of doing it! I have a few approaches in mind, but I want to make sure that whatever I do will play nicely with the new backend too.

**Comment by rebeccaringuette** [comment]
Sure. Thanks for all the work. I did some testing to see what values trigger the error. Given nine spherical coordinate positions...
```py
sat_time = np.repeat(1068865200, 9)  #UTC timestamps
sat_lon = np.array([-180.,-180.,-180.,0.,0.,0.,180.,180.,180.])  #in degrees
sat_lat = np.array([-90.,0.,90.,-90.,0.,90.,-90.,0.,90.])  #in degrees
sat_radius = np.repeat(1.063871355909377,9)  #in R_earth        
```
and converting between every possible coordinate pair,
```py
coord_list = ['GDZ','GEO','GSM','GSE','SM','GEI','MAG','SPH','RLL']
```
The error pops up for lat=-90 degrees at all longitude values tested and for coordinate conversions from GEO to GDZ, GEI to GDZ, SPH to GDZ, and RLL to GDZ. It does not occur for lat=0 or lat=90 degrees, or for any other coordinate conversion combination. The fix I have in on the Kamodo side is to catch the negative altitude, shift the latitude by 0.000000001 R_E away from the pole (e.g. lat=-89.999999999 deg), and rerun the coordinate conversion with the new latitude for the coordinate sets with the nonsense results. The new altitude value I get is 421.34775778 km. So, it looks like the North pole is indeed fine, but that the error occurs at all longitudes at the South pole. 

As for the efficiency, my testing shows the datetime object method to perform faster on average than the direct timestamp approach, even including our conversion time from timestamp to datetime object. Using the same testing approach as above, the ratio of completion times were compared between the original string method, the datetime object method and the direct timestamp method, each individually to the original datetime string method and also to each other (see table below). The ratios were chosen so the slower method was on top with the faster method on the bottom to indicate how many times faster the 'new' method would be as compared to the 'old' one. All comparisons were between identical coordinate conversions (e.g. GSM sph to GEO sph). For reference, the code for each method is:
```py
#datetime string method:
@np.vectorize
def ts_to_spacepystr(ts):
    return dt.strftime(dt.utcfromtimestamp(int(ts)), '%Y-%m-%dT%H:%M:%S')
tt = Ticktock(ts_to_spacepystr(sat_time), 'ISO')
    
#datetime object method
@np.vectorize
def ts_to_spacepydt(ts):
    return dt.fromtimestamp(ts, tz=timezone.utc)
tt = Ticktock(ts_to_spacepydt(sat_time), 'UTC')

#direct timestamp method
tt = Ticktock(sat_time, 'UNX')

```
Note that 'sat_time' is an array of utc timestamps as above.

    Avg   Std.Dev. Min   Max
    ---------------------------------
    2.05  0.67       1.00  6.2   ratio = str/dt completion times
    1.46  0.52       0.43  4.4   ratio = str/ts completion times
    1.52  0.69       0.73  4.8   ratio = ts/dt  completion times
    
Result: The datetime method is the fastest of the three tested, although within uncertainties of the direct timestamp method. In addition, the datetime method is never slower than the string method unlike the timestamp method. If you're curious, the datetime method was 0.55 (+/- 0.32) ms faster on average than the string method, and 0.24 (+/- 0.34) ms faster on average than the direct timestamp method. Given this test was done for nine coordinates, I hope the change greatly reduces our execution time when we deal with tens to hundreds of thousands of conversions at once. Thanks again for the help!

**Comment by jtniehof** [comment]
It doesn't necessarily surprise me that using datetimes directly is faster, particularly with the numpy vectorization, since the UNX to datetime conversion is via TAI. I haven't looked at optimizing that. UNX to TAI looks reasonable so I'm guessing cycles get burned in TAI to datetime (UTC); there's some dance back and forth to correct (and then uncorrect) for leap seconds. There was a good reason for that but I don't entirely remember (probably to avoid loops in the conversion dependencies.) 

One wrinkle to be aware of: SpacePy's handling of datetime is leapsecond-aware, i.e. although the leapseconds are not representable, they are properly handled. The assumption we make in handling Unix time is that the Unix clock freezes during the leap second. This is equivalent to the handling in utcfromtimestamp, which simply assumes the entire world freezes during the leap second. Some others may assume that the Unix clock remains running and the conversion to UTC changes.

This results in oddities like this:
```python
datetime.datetime(2017, 1, 1) - datetime.datetime(2016, 12, 31, 23, 59, 59) # timedelta(0, 1)
spacepy.time.Ticktock(datetime.datetime(2017, 1, 1)) - spacepy.time.Ticktock(datetime.datetime(2016, 12, 31, 23, 59, 59)) # timedelta(0, 2)
spacepy.time.Ticktock(datetime.datetime(2017, 1, 1)).UTC - spacepy.time.Ticktock(datetime.datetime(2016, 12, 31, 23, 59, 59)).UTC # timedelta(0, 1)
```

**Comment by rebeccaringuette** [comment]
My focus is model output, which has typical time resolutions of 1 minute at best, so a difference of a second here and there doesn't really concern me. It might be a concern with observational data, but I would be surprised if it was noticeable.
Thanks, Steve and Jon, for all the feedback, and good luck with the new backend.
