### ISSUE TITLE
Test failure in test_datamodel test_toRecArray

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#62]
Python 2.7, Windows 32-bit, dmarrayTests.test_toRecArray fails on line 457 (assertTrue ra.type in blah blah)

**Comment by jtniehof** [comment]
Also fails on Python 3.6, 32-bit Windows.

**Comment by drsteve** [comment]
To expand on this (Python 2.7, 64-bit, Windows), the failure is due to the expectation that the integer type will be '<i8' (aka int64). However, the dtype is identical between the variables in the SpaceData and the recarray.

The following test does not raise an AssertionError
```
for key in sd:
    assert sd[key].dtype == ra.dtype[key]
```

I believe that this test failure is a test issue and not a code issue.
toRecArray uses the same default/auto-identified data types as dmarray.

However, the dtype isn't guaranteed to be preserved. Forcing the dtype by setting `sd['y'] = dm.dmarray([2, 4], dtype=np.int64)` leads to `sd['y'].dtype` being int64, and the default type (int32) is still used by recarray.

I think this is two issues:
- test_toRecArray should be changed to test for only equality of keys and contents (not data type)
- we need new tests for preservation of explicitly set types. This will fail right now. To make that pass we'll need to explicitly pass the dtypes from the source arrays into the constructor for the recarray.

I don't think this is actually a specific windows issue, just that it became visible on windows due to the test construction. So I'm going to remove the Windows tag from the issue.

How does the rest of this sound? Should I move ahead with the proposed fixes?
