### ISSUE TITLE
Make next steps more obvious when no fortran compiler is present

### ISSUE THREAD

**Issue by johncoxon** [spacepy/spacepy#622]
I've just had a student in who's been struggling to get SpacePy compiling on her Mac, and the issue was that `pip install spacepy` failed due to there not being a `gfortran` install present on the machine. Installing homebrew and using that to install `gcc` in this circumstance solves this issue (or at least, it did on her machine just now) – is there a way to have the Terminal tell you that that's the fix for the issue if you're in this situation? Something like printing to the shell, "you don't have gfortran installed so you should install homebrew and then run `brew install gcc` prior to running `pip install spacepy`"?

**Comment by jtniehof** [comment]
The problem is that pip eats the shell output, which already includes a warning that irbem didn't compile. 0.4.0 has quite a few updates for installation, both code and docs, particularly #639, that should ameliorate this.

Other than that, I think the best we can do is document how to get the verbose log out of pip, so I'm marking this a documentation issue and will take that on.

**Comment by johncoxon** [comment]
Thanks Jon, I appreciate it!
