### ISSUE TITLE
Test failure test_datamodel.JSONTests.test_toHTML

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#63]
Fails on the file size check, line 721.
Fails: 32-bit Windows, Python 3.6; 64-bit Windows, Python 3.6
Succeeds: 32-bit Windows, Python 2.7; 64-bit Windows, Python 2.7.

**Comment by drsteve** [comment]
Since GEM is coming up, there's a Python for Space Science tutorial session there, and we've had some *major* updates and fixes in recent months, I'm going to suggest we do a release ASAP.

I know there are still some Windows issues, and ideally they'd all be fixed before a release. However, our current release doesn't work for far more users (or potential users) than would be disadvantaged by a slightly buggy Windows release. Also, our last Windows release has just graduated from kindergarten.

To help progress towards that, I was trying to work through some of these Windows bugs.

This one looks like a combination of _kind of weird test_ and not accounting for the Python 2/3 difference on the Windows side.

Works for me on Windows (64-bit, Python 3.7) when I change the expected value to match the difference in unicode behavior from 2 to 3.

I.e.,
```
        if sys.platform == 'win32':
            if str is bytes:
                expected = 12916 #different line-endings
            else:
                expected = 12892
```

**Comment by jtniehof** [comment]
Agree with your solution. It would be great to have a more robust test (parse the HTML?) but for now this'll be fine. It might be worth compacting:
```
if sys.platform == 'win32': #Different line endings
    expected = 12916 if str is bytes else 12892
else:
    expected = 12834 if str is bytes else 12892 #no u on unicode strings
```

Regardless this should be an easy one.

**Comment by drsteve** [comment]
I'll throw a PR together. Will probably just use your compact Python-ternary version.
