### ISSUE TITLE
Test failure: test_poppy.AssocTests.testAssocBootstrapRegress

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#67]
Error on 64-bit Windows, python 2.7 and Python 3.6, line 507 of poppy, on initializing lag_seeds: `ValueError: low is out of bounds for int32`.

Works on 32-bit Windows, python 2.7 and 32-bit Windows, Python 3.6.

**Comment by drsteve** [comment]
Just built SpacePy on 64-bit Windows, Python 3.7 under Anaconda. 
I get no failures from test_poppy.py.

I built spacepy from source after manually following the steps in the Windows setup script in a new Anaconda environment, then `python setup.py install --fcompiler=gnu95`

**Comment by drsteve** [comment]
I've taken a closer look at this one too.

Basically, I don't think this is expected to work on 64-bit Python on Windows.
See, e.g. the discussion at (https://github.com/numpy/numpy/pull/6910)
and several of the answers at (https://stackoverflow.com/questions/36797420/easiest-way-to-generate-random-int64-array-in-numpy)

Basically, on Windows `numpy.random.randint` assumes 32-bit (regardless of 32- or 64-bit Python). As of numpy 1.11 explicit dtypes can be passed in so 64-bit can be requested.

So, how do we want to fix this?
 1. fix the range of requested random integers to be 32-bit, regardless of system
 2. require numpy>=1.11 and set the dtype based on sys.maxsize
 3. treat all windows installs as 32-bit and special case the code

Do any have particular advantages or disadvantages?


Additional thought while staring at PoPPy code... there's still a check in there for Python versions pre-2.6 that tells users to upgrade to numpy>=1.6. Since we don't support Python 2.6 (let alone older versions) any more, and our minimum supported version of numpy is 1.6, we should remove this check.

**Comment by jtniehof** [comment]
Given the TODO, I'm in favor of something that lets us use unsigned ints, so that lets us fix both. Ubuntu 16.04 has 1.11 and it came out in 2016. I'm not sure I like requiring it just for this....

How about we replace the 1.6 warning about reduced entropy with a 1.11 warning about reduced entropy, use the new interface if 1.11 and later, and accept the test failure? (or special-case the skip to also skip if on Windows and numpy <1.11)

Hopefully this won't change the "expected"!

**Comment by jtniehof** [comment]
Ugh, I realized we will lose reproducibility if we explicitly specify unsigned dtype. I'm working a PR now.
