### ISSUE TITLE
Coordinate conversion data changes size for conversion into GDZ sph.

### ISSUE THREAD

**Issue by rebeccaringuette** [spacepy/spacepy#673]
I found a bug when converting a set of coordinates from GSE sph to GDZ sph (first pic). The size of the data changes. This doesn't occur with the other coordinate conversions I've tested (e.g. GSE sph to GEO sph, second pic). 

### Minimal example to reproduce issue:
```py
# spacepy coord object created with:
sat_track = [[c3[i], c2[i], c1[i]] for i in range(len(c1))]   # c1 is lon, c2 is lat, c3 is radius, all length of 10 for this example
coord_obj= Coords(sat_track, 'GSE', 'sph')
coord_obj.ticks = Ticktock(inTime, 'UTC')   # inTime is an array of 10 datetime objects in UTC, all for the same time
gdz_coord = coord_obj.convert('GDZ', 'sph') 
print(coord_obj.data.shape, gdz_coord.data.shape)  # output is (10, 3), (3, 3) -> This breaks later code in my workflow.
geo_coord = coord_obj.convert('GEO', 'sph')
print(coord_obj.data.shape, geo_coord.data.shape)  # output is (10, 3), (10, 3) -> as expected.
```
Example with GDZ coordinate conversion (breaks later code due to size change):
![image](https://user-images.githubusercontent.com/49281118/203391942-4a4785dd-f31a-4385-a389-74b38add8dd1.png)

Example with GEO coordinate converion (works fine):
![image](https://user-images.githubusercontent.com/49281118/203392028-6c9a9ddc-dbf1-4ceb-b17d-fe06673a8fef.png)

Windows-10-10.0.19041-SP0
sys.version_info(major=3, minor=7, micro=13, releaselevel='final', serial=0)
numpy=1.21.5
scipy=1.7.3
matplotlib=3.5.2
spacepy=0.3.0

installation instructions for this spacepy: python -m pip install --upgrade spacepy

**Comment by drsteve** [comment]
Thanks for the report.
I can't reproduce under 0.4.0rc0 (just what was installed on this laptop), but I've not looked at a specific windows build (there's no reason I can see that this would be platform-dependent though). After the test below I updated (using `pip install --upgrade --no-build-isolation spacepy`) to 0.4.1 and obtained the same results.

Because the example provided isn't complete (`c1`, `c2`, `c3`, and `inTime` aren't specified) I've done the following (which should illustrate the same conversions):

```
(default) sm:~$ ipython
Python 3.9.7 (default, Sep 16 2021, 13:09:58)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.27.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import spacepy.coordinates as spc

In [2]: import spacepy.time as spt

In [3]: ticks = spt.tickrange('2017-01-10T12:00:00','2017-01-11T00:00:00', 1.25/24)

In [4]: pos = spc.Coords([[2, 29., 54.]]*10, 'GSE', 'sph', use_irbem=False, ticks=ticks)

In [5]: p2 = pos.convert('GDZ', 'sph')

In [6]: pos.shape, p2.shape
Out[6]: ((10, 3), (10, 3))

In [7]: pos = spc.Coords([[2, 29., 54.]]*10, 'GSE', 'sph', use_irbem=True, ticks=ticks)

In [8]: p2 = pos.convert('GDZ', 'sph')

In [9]: pos.shape, p2.shape
Out[9]: ((10, 3), (10, 3))

In [10]: print(pos)
Coords( [[2.0, 29.0, 54.0], [2.0, 29.0, 54.0], [2.0, 29.0, 54.0], [2.0, 29.0, 54.0], [2.0, 29.0, 54.0], [2.0, 29.0, 54.0], [2.0, 29.0, 54.0], [2.0, 29.0, 54.0], [2.0, 29.0, 54.0], [2.0, 29.0, 54.0]] , 'GSE', 'sph')

In [11]: print(p2)
Coords( [[6366.512158016664, 20.640490330516787, 43.954204421275215], [6366.51688656269, 20.659541787430463, 25.19810714100511], [6366.521620553967, 20.678600415803167, 6.442011847736481], [6366.52635998941, 20.697666203438317, -12.314081448218312], [6366.531104867915, 20.716739138126336, -31.07017273652867], [6366.535855188355, 20.73581920765277, -49.826262006848005], [6366.540610949601, 20.75490639980401, -68.58234924881494], [6366.545372150514, 20.77400070236124, -87.33843445205294], [6366.550138789922, 20.793102103092817, -106.09451760616663], [6366.554910866643, 20.812210589773304, -124.85059870074778]] , 'GDZ', 'sph')
```
One difference is that my times don't have timezone information (which I generally advise stripping from the `datetime` unless you have a good reason to keep it... a UTC timezone is redundant here). I am not convinced that there's any way that'd be breaking things here.

I recall an issue with array conversions of GDZ that I thought was patched prior to the 0.3 release, but if you're using 0.3.0 I'd suggest updating to 0.4.x. If you still see this issue with 0.4.x then I'll try to dig a little deeper.
