### ISSUE TITLE
Consistency Creating NRV Variables 

### ISSUE THREAD

**Issue by Alrobbertz** [spacepy/spacepy#707]
I'm seeing inconsistent behavior creating NRV variables. 

I create a test CDF File:
```python
from spacepy.pycdf import CDF
c = CDF(pathname="test.cdf", masterpath="")
```

I try to add an empty variable, and set to NRV in two separate lines:
```python
c.new("test", data=[])
_ = c["test"].rv(False)
c["test"]
```
And this works as expected:
```
<Var:
CDF_FLOAT [] NRV
>
```

I try to add an empty variable, and set to NRV in a single line:
```python
c.new("test1", data=[], recVary=False)
c["test1"]
```
But now I get a `CDFError`
```
ERROR: CDFError: BAD_DIM_SIZE: Dimension size specified as zero or less. [spacepy.pycdf]
```

I try to add a non-empty variable, and set to NRV in two separate lines:
```python
c.new("test2", data=[1,2])
_ = c["test2"].rv(False)
c["test2"]
```
But get a `CDFError`:
```
ERROR: CDFError: CANNOT_CHANGE: The parameter/value can't be set/changed. [spacepy.pycdf]
```

I try to add an non-empty variable, and set to NRV in a single line:
```python
c.new("test3", data=[1,2], recVary=False)
c["test3"]
```
And this now works as expected:
```
<Var:
CDF_BYTE [2] NRV
>
```

Is this known/ intended behavior? I'd like to use one approach consistently, either one call to `new()`, or with a second call to `rv()` but it seems like the behavior is different depending on whether the `data` is empty or not. 

### OS, Python version, and dependency version information:
```
macOS-13.5-arm64-arm-64bit
sys.version_info(major=3, minor=8, micro=16, releaselevel='final', serial=0)
numpy=1.24.2
scipy=1.10.1
matplotlib=3.7.1
```

### Version of SpacePy
```
spacepy=0.4.1
```
Installed from `pip`

**Comment by jtniehof** [comment]
Thanks for the input, Andrew. Going through each case...

> ```python
> from spacepy.pycdf import CDF
> c = CDF(pathname="test.cdf", masterpath="")
> ```

Fine, althogh this would also work:
```python
c = CDF("test.cdf", create=True)
```
(The empty master path thing was always a hack and I finally added the create kwarg to the [CDF class](https://spacepy.github.io/autosummary/spacepy.pycdf.CDF.html#spacepy.pycdf.CDF) in 0.2.0.)


> ```python
> c.new("test", data=[])
> _ = c["test"].rv(False)
> c["test"]
> ```
> 
> And this works as expected

Looks good.

> I try to add an empty variable, and set to NRV in a single line:
> 
> ```python
> c.new("test1", data=[], recVary=False)
> c["test1"]
> ```
> 
> But now I get a `CDFError`
> 
> ```
> ERROR: CDFError: BAD_DIM_SIZE: Dimension size specified as zero or less. [spacepy.pycdf]
> ```

I agree that's surprising and this is the crux. A few related examples:

If a type is specified instead of data the NRV default is a scalar:

```python
c.new('test1', recVary=False, type=spacepy.pycdf.const.CDF_INT1)
c['test1'].shape  # ()
```

But passing an empty list as the data for NRV implies a single dimension of size zero. (By analogy with RV, where doing this makes a scalar variable with the record dimension empty...so the record dimension has to become a "normal" one). This is pretty much exactly what's happening there. There's not much point to having an NRV variable with all zero-length dims, because you could never put anything in there...thus the CDF library complains.

Your best option if you want to create NRV without any data would be to explicitly specify the type and dims:
```python
c.new('test1', recVary=False, type=spacepy.pycdf.const.CDF_INT1, dims=[3, 3])
```

A CDF variable cannot be redimensioned once it is created--only the record dimension can grow/shink. (I don't recall if this is a strict creation limit or an after-data-are-written limit but it's weird enough that I didn't bother implementing a redimension interface.)

So the question is, what dimensions do you expect the variable to have after:
```python
c.new("test1", data=[], recVary=False)
```

It's not clear there's a "right" answer; see #16 and #17 for related.

> I try to add a non-empty variable, and set to NRV in two separate lines:
> 
> ```python
> c.new("test2", data=[1,2])
> _ = c["test2"].rv(False)
> c["test2"]
> ```
> 
> But get a `CDFError`:
> 
> ```
> ERROR: CDFError: CANNOT_CHANGE: The parameter/value can't be set/changed. [spacepy.pycdf]
> ```

That's correct, record variance cannot be changed after a variable is written.

> I try to add an non-empty variable, and set to NRV in a single line:
> 
> ```python
> c.new("test3", data=[1,2], recVary=False)
> c["test3"]
> ```
> 
> And this now works as expected:

Yep, that's expected.

**Comment by Alrobbertz** [comment]
Jon, thank you for the details and some good extra examples. I'll have some code thats a switch on whether the data is scalar or not to set the dims correctly. This exercise also showed me that I'm not reading scalar data correctly either so I appreciate the insight.
