### ISSUE TITLE
Coordinates transformation: continuous times but stepwise result for ctrans backend

### ISSUE THREAD

**Issue by billism** [spacepy/spacepy#734]
I did some coordinates conversion test (from Geocentric to J2000), the result is a bit unexpected. please take a look at the following code and its output.

### Minimal example to reproduce issue:

```python
from spacepy import coordinates as coord
from spacepy.time import Ticktock

N=180
# repeated input Geocentric coordinates
source = [[1, 0, 0]] * N
# continuous time range
times  = pd.date_range(start="2023-03-05 12:00:00",end="2023-03-05 12:02:59", periods=N).to_pydatetime()
print(times[:3])

source_coords = coord.Coords(data=source, dtype='GEO', carsph='car', units=['Re','Re','Re'], use_irbem=False)
source_coords.ticks = Ticktock(times, 'UTC')
target_coords = source_coords.convert('J2000', 'car')

fig, [ax1, ax2, ax3] = plt.subplots(3, 1, figsize=(10,5))
ax1.plot(times, target_coords.data[:,0])
ax2.plot(times, target_coords.data[:,1])
ax3.plot(times, target_coords.data[:,2])

plt.show()
```
![image](https://github.com/spacepy/spacepy/assets/2051631/067f9e48-d32e-4714-9e89-0ed94293d8c7)

however, if I use irbem backend (set `use_irbem=True`, the result is smooth:
![image](https://github.com/spacepy/spacepy/assets/2051631/ea4d88d1-6fc8-4c25-bb96-f5f658bc4f06)

### OS, Python version, and dependency version information:
OS: Windows 10
Python: 10 (mini conda environment)

### Version of SpacePy
SpacePy Version: '0.4.1'

**Comment by drsteve** [comment]
By default the SpacePy backend for coordinate transformations caches the transformation matrices and only recalculates them at a (user-defined) cadence. See https://spacepy.github.io/coordinates.html#setting-options-for-coordinate-transformation

As shown in your figures, the default `itol` is 30 seconds. This is primarily to ensure that the most common use cases balance speed and precision, since the calculation of coordinate frame rotations is slower than the evaluation of those transformations and, more importantly, most of the frames actually move slowly with respect to each other. In cases where you need the extra precision, you can set the cadence of transform recalculation using
```
>>> import spacepy.coordinates as spc
>>> spc.DEFAULTS.set_values(itol=5)  # itol is given in seconds
```
setting `itol` to zero will force the transforms to be recalculated for every coordinate conversion, regardless of whether the time is the same, two microseconds apart, or 20 seconds apart. If you're calculating a lot of transforms for the same timestamp, setting this to zero is not efficient. On the flip side, if you're looking at sub-second data and the _precise_ position is important, then setting `itol=0` is the right thing to do.

**Comment by billism** [comment]
this solves my question.
thank you so much !

**Comment by billism** [comment]
this solves my question.
thank you so much !
