### ISSUE TITLE
pycdf.istp.FileChecks.all fails : TypeError: '<' not supported between instances of 'float' and 'datetime.datetime'

### ISSUE THREAD

**Issue by xbonnin** [spacepy/spacepy#752]
Hello,

I have an issue when I run istp check for the CDF file solo_L1_rpw-tds-surv-stat-cdag_20230402_V01.cdf (available in https://rpw.lesia.obspm.fr/roc/data/pub/shared/outgoing/solo_L1_rpw-tds-surv-stat-cdag_20230402_V01.cdf).

I'm not sure to know where the problem comes from. 
At a first glance, the CDF file looks well formed, but maybe not.

Thanks for help.

### Minimal example to reproduce issue:

```
cdf = 'solo_L1_rpw-tds-surv-stat-cdag_20230402_V01.cdf'
with pycdf.CDF(str(rpw_cdf)) as cdf:
    result = pycdf.istp.FileChecks.all(cdf)
```

### Error message/Traceback:
```
Traceback (most recent call last):
  File "/obs/xbonnin/software/DataPool/SOLO/RPW/CDF/Tools/check_rpw_cdf.py", line 1054, in main
    result = pycdf.istp.FileChecks.all(cdf)
  File "/home/xbonnin/.virtualenvs/mypy/lib/python3.8/site-packages/spacepy/pycdf/istp.py", line 731, in all
    for e in VariableChecks.all(f[v], catch=catch)))
  File "/home/xbonnin/.virtualenvs/mypy/lib/python3.8/site-packages/spacepy/pycdf/istp.py", line 129, in all
    errors.extend(f(v))
  File "/home/xbonnin/.virtualenvs/mypy/lib/python3.8/site-packages/spacepy/pycdf/istp.py", line 587, in validscale
    return cls._validhelper(v, False)
  File "/home/xbonnin/.virtualenvs/mypy/lib/python3.8/site-packages/spacepy/pycdf/istp.py", line 505, in _validhelper
    if numpy.any((minval > attrval)) or numpy.any((maxval < attrval)):
TypeError: '<' not supported between instances of 'float' and 'datetime.datetime'
```

### OS, Python version, and dependency version information:
Run on Debian 12, Python 3.11, numpy 1.24.4

### Version of SpacePy
0.6

**Comment by jtniehof** [comment]
Hi Xavier--

Nice to see someone actually using the istp checks! The problem is that sometimes the CDF doesn't validate in an unexpected way.

Here the problem is the typing of the SCALEMAX/SCALEMIN on Epoch:
```
cdf['Epoch'].attrs
<zAttrList:
CATDESC: Default time [CDF_CHAR]
DISPLAY_TYPE: time_series [CDF_CHAR]
FIELDNAM: Epoch [CDF_CHAR]
FILLVAL: 9999-12-31 23:59:59.999999 [CDF_TIME_TT2000]
FORMAT: F20.0 [CDF_CHAR]
LABLAXIS: Epoch [CDF_CHAR]
MONOTON: INCREASE [CDF_CHAR]
REFERENCE_POSITION: Spacecraft barycenter [CDF_CHAR]
Resolution: 15258 ns [CDF_CHAR]
SCALEMAX: 7.337522133815899e+17 [CDF_DOUBLE]
SCALEMIN: 7.336658292244118e+17 [CDF_DOUBLE]
SCALETYP: linear [CDF_CHAR]
SI_CONVERSION: 1.0E-9>s [CDF_CHAR]
TIME_BASE: J2000 [CDF_CHAR]
TIME_SCALE: Terrestrial Time [CDF_CHAR]
UNITS: ns [CDF_CHAR]
VALIDMAX: 2029-12-31 23:59:59.999000 [CDF_TIME_TT2000]
VALIDMIN: 2000-01-01 12:00:00 [CDF_TIME_TT2000]
VAR_NOTES: Primary time used as a reference in the file [CDF_CHAR]
VAR_TYPE: support_data [CDF_CHAR]
>
```

Epoch is CDF_TT2000 and the DOUBLE isn't the same type (or equivalent). pycdf isn't doing an explicit type check on the SCALEMIN/SCALEMAX (or VALIDMIN/MAX) to try to be friendly, but it's being overly generous on datetime. This should give a validation failure that the CDF_DOUBLE isn't comparable to the variable type CDF_TT2000.

We should be able to get this in as a test case and have the appropriate validation failure, but the CDF does need to be fixed.

The `all()` check methods support a [catch](https://spacepy.github.io/autosummary/spacepy.pycdf.istp.FileChecks.html#spacepy.pycdf.istp.FileChecks.all) kwarg to catch exceptions and continue. If you use that here:
```
spacepy.pycdf.istp.FileChecks.all(cdf, catch=True)
["Logical_file_id solo_L1_rpw-tds-surv-stat_20230402_V01 doesn't match filename solo_L1_rpw-tds-surv-stat-cdag_20230402_V01.cdf.",
 'Epoch: multiple days 20230402, 20230403.',
 'Epoch: [Test validscale did not complete](https://spacepy.github.io/autosummary/spacepy.pycdf.istp.FileChecks.html#spacepy.pycdf.istp.FileChecks.all).',
 'ACQUISITION_TIME: FIELDNAM attribute CCSDS CUC Acquisition time as returned in TM packets does not match var name.',
 'ACQUISITION_TIME: Multi dim variable with time_series display type.',
 'QUALITY_BITMASK: SCALEMIN type CDF_UINT1 does not match variable type CDF_UINT2.',
 'QUALITY_BITMASK: SCALEMAX type CDF_UINT1 does not match variable type CDF_UINT2.',
 'BIA_STATUS_INFO: Multi dim variable with time_series display type.',
 'RPW_STATUS_INFO: Multi dim variable with time_series display type.',
 'SN_THRESHOLD: SCALEMIN type CDF_UINT2 does not match variable type CDF_UINT1.',
 'SN_THRESHOLD: SCALEMAX type CDF_UINT2 does not match variable type CDF_UINT1.',
 'ACQUISITION_TIME_UNITS: No FILLVAL attribute.',
 'ACQUISITION_TIME_LABEL: No FILLVAL attribute.',
 'CHANNEL_STATUS_INFO: Multi dim variable with time_series display type.',
 'CHANNEL_LABEL: No FILLVAL attribute.',
 'SCET: FIELDNAM attribute Spaceraft Elapsed Time does not match var name.']
```
"Epoch: Test validscale did not complete." means there was an exception in running the validscale test.

BTW the FIELDNAM and display type checks are overly picky and should be relaxed...there was a particular interpretation at one point in time that was set in stone here erroneously.

**Comment by jtniehof** [comment]
Test case to generate: crib off testValidScale. Make a CDF_TT2000 variable, set SCALEMIN/SCALEMAX to CDF_DOUBLE, validscale should return the 'SCALEMIN type CDF_DOUBLE not comparable to variable type CDF_TT2000.'
