### ISSUE TITLE
Document required packages and versions

### ISSUE THREAD

**Issue by balarsen** [spacepy/spacepy#8]
We need to document the requirements better and capture the versions of each that are required. I propose that the best way to do this is a document page describing the flow and creation of `requirements.txt` with minimum versions for each package.

**Comment by balarsen** [comment]
I started this and it seems to be more manual than I had hoped. When I have the right computer I will punch in what I have found so far.

**Comment by drsteve** [comment]
Adding some info... addressing the deprecated color cycler in our plot styles implies a requirement of matplotlib>=1.5. Requiring that version means we're automatically bumped to numpy >=1.6. As best I can tell that puts us at scipy >=0.10 to be safe. Alongside the mplstyle fixes I'll update the requirements in setup. I'm noting this here so there's an easy-to-find rationale.

Note that these are strict minimum versions, not a suggestion for what we *should* support.

**Comment by jtniehof** [comment]
Those aren't particularly arduous.
Debian stable: matplotlib 2.0, scipy 0.18, numpy 1.12
Ubuntu 16.04LTS: matplotlib 1.5, scipy 0.17, numpy 1.11

I suggest we: 1) document why we need a particular version (not every single call, just the strictest requirement) 2) only require a version we actually need for some reason 3) if it's available in the LAST Ubuntu LTS and the latest Debian stable, consider that okay. Alternative would be to target the oldest supported Ubuntu LTS and oldest supported CentOS?

Ubuntu 14.04LTS: matplotlib 1.3, scipy 0.13, numpy 1.8 --so supporting this would require special-casing the color cycler.

I find the RH-derived distros MUCH harder to find package information for. Looks like CentOS 6 is current oldest supported. matplotlib 0.99, scipy 0.7.2, numpy 1.4. CentOS 7: matplotlib 1.2, scipy 0.12, numpy 1.7.

I feel we have a hard time requiring matplotlib 1.5 if the latest CentOS doesn't support it.

**Comment by drsteve** [comment]
So for having the mplstyle files compatible with the latest matplotlib (issue #22 ) we need to remove the color cycler and change it to a properties cycler. The properties cycler is only supported from matplotlib 1.5, which is when the color cycler was deprecated.
If we want to support both <1.5 and >=2.2.3 then we need different style files and the install needs to take the right ones. It's not a matter of special casing the color cycler so much as special casing which style file is used.

Given the ease of using pip (or conda), I'm not convinced that we need to work with the repo versions of CentOS6 (or even 7). It's not like pip or conda require admin privilege to install...
CentOS6 has Nov. 2020 as EOL. Python 2's official end-of-life is before that. Actually, CentOS6 has Python 2.6 rather than 2.7, so we already don't really support it...

For now I'm comfortable with the list @jtniehof gave. That is, document, require a *reason*, and try to stay with what's in the last Ubuntu LTS and Debian stable (or older).

**Comment by drsteve** [comment]
I'll be commenting on issue #22 in a minute, but I have a candidate branch that I'd like to submit a PR on that fixes a number of issues with matplotlib deprecations, and fully resolves #22 

As I mentioned before, I *think* this implies matplotlib>=1.5, which (in turn) implies numpy>=1.6.
My updates in that candidate branch (mpl_updates on drsteve/spacepy) include updating the minimum versions:
matplotlib: from >=0.99 to >=1.5
numpy: from >=1.4 to >=1.6
scipy: from >=0.7 to >=0.10

In addition, I believe we are explicitly only compatible with 2.7 and 3.x, but I'm not sure what the x covers. Our CI tests 3.5 and 3.6.

While we'll still need to actually explicitly document our version requirements, **I'd like to get opinions on the numpy/scipy/mpl versions given above. Are we okay bumping our requirements?** To support the most recent matplotlib release we're going to need to have changes that break compatibility with older matplotlib. The alternative is to have version testing and style files that are for old/new versions of matplotlib, and I don't like that solution.

**Comment by jtniehof** [comment]
For 3.x, I usually want 3.2. IIRC, 2.6 was supposed to be the "version of 2.x that's most like 3.0" but some stuff from 3.1 slipped in; similarly 2.7 was supposed to be "version of 2.x that's most like 3.1" but some 3.2 slipped in. So 2.7 + 3.2 is sort of peanut butter and jelly, and I think we should stick to that for now, with the caveat that people really shouldn't be on 3.2 without a dang good reason since we test 3.5 more heavily. And I'm okay with your bumps. I'd like to support CentOS and Scientific Linux but they haven't had a major release in four years. I just don't think we can tag along that long.

Note matplotlib has pledged not to support Python 2 after 2020, along with all our other requirements. I think we should set a timeline for phasing out Python 2, but that's a discussion we can start having after I get the next dang release out. https://python3statement.org/

**Comment by drsteve** [comment]
As discussed in #30 and #24 some configurations will fail to install when using numpy 1.15.0, so we should exclude that in any requirements (see also #38 ) and note this in documentation.

**Comment by jtniehof** [comment]
We've got to make the "necessary" vs. "needed for some things" distinction clear again. I know I lost that argument internally, but now I've heard five different people say "I wanted to use pycdf but I couldn't get the Fortran to work so I just reimplemented it/gave up/ripped out that code myself."

**Comment by drsteve** [comment]
I would keep pycdf as core, since datamodel needs it. But irbempy could
easily come out once coordinates has been disengaged from the Fortran.

**Comment by jtniehof** [comment]
When complete, this should capture the ffnet information from #160 and #161

**Comment by jtniehof** [comment]
Where are we even at on this one? @balarsen did you "punch in what you have so far"? There's a lot of good discussion but it's hard to determine what would constitute "closed" on this issue.

**Comment by balarsen** [comment]
@jtniehof I am in favor of closing this is documented in requirements.txt to a large extent.

**Comment by graingert** [comment]
how about using `extras_require`? then people can `pip install spacepy[feature]`

**Comment by balarsen** [comment]
> how about using `extras_require`? then people can `pip install spacepy[feature]`

I like this solution, I don't know to do it but can also solve #160

**Comment by graingert** [comment]
Can we compile everything to wasm and use python-ext-wasm?

**Comment by jtniehof** [comment]
Can we keep this issue on the specific documentation topic and open others for enhancements?
